In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import time
import random
from torchinfo import summary
import optuna
import tqdm as notebook_tqdm
from data_handler import *
from uncertainty import *
from linear_variational import *

# 4th GPU on AIMS02
device = torch.device('cuda:3')
print(f"Using device: {device}")
print(torch.cuda.get_device_name())

def set_random_seed(seed_value=42):
    # Python random seed
    random.seed(seed_value)
    
    # Numpy random seed
    np.random.seed(seed_value)
    
    # PyTorch seed
    torch.manual_seed(seed_value)
    
    # If using CUDA (GPU)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)  # if using multi-GPU
        torch.backends.cudnn.deterministic = True  # For reproducibility
        torch.backends.cudnn.benchmark = False  # Disable auto-optimization for determinism

set_random_seed()

Using device: cuda:3
NVIDIA RTX 6000 Ada Generation

In [9]:
# Load data
train = pd.read_csv('~/nureth/tf_and_ts/tuning/TF_TS_train.csv')
test = pd.read_csv('~/nureth/tf_and_ts/tuning/TF_TS_test.csv')
valid = pd.read_csv('~/nureth/tf_and_ts/tuning/TF_TS_valid.csv')

# Interpolate the NaN values
train['TS'] = train['TS'].interpolate()
test['TS'] = test['TS'].interpolate()
valid['TS'] = valid['TS'].interpolate()

# Function to find rows with NaN values in a pandas DataFrame
def check_nans_in_dataframe(df, column_name, name):
    nan_rows = df[df[column_name].isna()]
    if not nan_rows.empty:
        print(f"Rows with NaN values in {name} dataset:")
        print(nan_rows)
    else:
        print(f"No NaN values in {name} dataset.")

# Check for NaN values in each dataset
check_nans_in_dataframe(train, 'TS', 'Train')
check_nans_in_dataframe(test, 'TS', 'Test')
check_nans_in_dataframe(valid, 'TS', 'Validation')

No NaN values in Train dataset.
No NaN values in Test dataset.
No NaN values in Validation dataset.

In [10]:
# Preprocess the data
scaler = MinMaxScaler(feature_range=(0, 1))
train_data = scaler.fit_transform(train)
test_data = scaler.transform(test)
valid_data = scaler.transform(valid)

# Create sequences
def create_sequences(data, lookback=10):
    X, y = [], []
    for i in range(lookback, len(data)):
        X.append(data[i-lookback:i])  # Use the last 'lookback' time steps for prediction
        y.append(data[i])  # The next time step is the target
    return np.array(X), np.array(y)

timesteps = 10
Xtrain, Ytrain = create_sequences(train_data, lookback=timesteps)
Xtest, Ytest = create_sequences(test_data, lookback=timesteps)
Xvalid, Yvalid = create_sequences(valid_data, lookback=timesteps)

# Convert to PyTorch tensors
Xtrain_tensor = torch.tensor(Xtrain, dtype=torch.float32).to(device)
Ytrain_tensor = torch.tensor(Ytrain, dtype=torch.float32).to(device)
Xtest_tensor = torch.tensor(Xtest, dtype=torch.float32).to(device)
Ytest_tensor = torch.tensor(Ytest, dtype=torch.float32).to(device)
Xvalid_tensor = torch.tensor(Xvalid, dtype=torch.float32).to(device)
Yvalid_tensor = torch.tensor(Yvalid, dtype=torch.float32).to(device)

print(
    f"""Xtrain, Ytrain: {Xtrain_tensor.shape}, {Ytrain_tensor.shape}
Xtest,   Ytest: {Xtrain_tensor.shape}, {Ytrain_tensor.shape}
Xvalid, Yvalid: {Xvalid_tensor.shape}, {Yvalid_tensor.shape}"""
)

Xtrain, Ytrain: torch.Size([340060, 10, 2]), torch.Size([340060, 2])
Xtest,   Ytest: torch.Size([340060, 10, 2]), torch.Size([340060, 2])
Xvalid, Yvalid: torch.Size([170025, 10, 2]), torch.Size([170025, 2])

In [11]:
class vLSTM(nn.Module):
    def __init__(self, in_features, hidden_size1, hidden_size2, hidden_size3, out_features, prior_mean=0, prior_variance=0.5, posterior_rho_init=-4.0, bias=True):
        super(vLSTM, self).__init__()

        # Define multiple LSTM layers
        self.lstm1 = nn.LSTM(in_features, hidden_size1, batch_first=True)

        self.lstm2 = nn.LSTM(hidden_size1, hidden_size2, batch_first=True)

        self.lstm3 = nn.LSTM(hidden_size2, hidden_size3, batch_first=True)
        
        self.fc = LinearReparameterization(
            in_features=hidden_size3,
            out_features=out_features,
            prior_mean=prior_mean,
            prior_variance=prior_variance,
            posterior_rho_init=posterior_rho_init,
            bias=bias
        )

    def forward(self, x, hidden_states=None):
        # LSTM1
        out, _ = self.lstm1(x, hidden_states)
    
        # LSTM2
        out, _ = self.lstm2(out, hidden_states)

        # LSTM3
        out, _ = self.lstm3(out, hidden_states)

        # Get the output for the **last time step** only: [batch_size, hidden_size]
        hidden_last_step = out[:, -1, :]  # Last time step

        # Pass through the final linear layer
        output, kl_fc = self.fc(hidden_last_step)
        kl_total = kl_fc

        # Return output and total KL divergence
        return output, kl_total

In [17]:
# Define the Optuna objective function using your training loop
def objective(trial):
    # --- Hyperparameter suggestions ---
    lr = trial.suggest_loguniform("lr", 1e-5, 1e-1)
    batch_size = trial.suggest_categorical("batch_size", [256, 512])
    hidden_size1 = trial.suggest_int("hidden_size1", 16, 128, step=16)
    hidden_size2 = trial.suggest_int("hidden_size2", 16, 128, step=16)
    hidden_size3 = trial.suggest_int("hidden_size3", 8, 64, step=8)
    
    # Optionally, choose a KL schedule
    kl_schedule = "sigmoid_decay"

    # --- Instantiate the variational model ---
    # (Adjust in_features and out_features as needed for your data)
    in_features = 2
    out_features = 2
    model = vLSTM(
        in_features=in_features,
        hidden_size1=hidden_size1,
        hidden_size2=hidden_size2,
        hidden_size3=hidden_size3,
        out_features=out_features,
        prior_mean=0,
        prior_variance=0.5,
        posterior_rho_init=-4.0,
        bias=True
    ).to(device)

    # --- Optimizer and loss ---
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    reconstruction_loss_fn = nn.L1Loss()  # or nn.MSELoss()

    # --- DataLoaders for training and validation ---
    train_dataset = torch.utils.data.TensorDataset(Xtrain_tensor, Ytrain_tensor)
    val_dataset   = torch.utils.data.TensorDataset(Xvalid_tensor, Yvalid_tensor)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
    val_loader   = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    num_epochs = 30
    # Track the validation loss from each epoch so that we can report to Optuna
    for epoch in range(num_epochs):
        model.train()

        # --- Update KL weight based on schedule ---
        if kl_schedule == 'linear':
            kl_weight = epoch / num_epochs
        elif kl_schedule == 'sigmoid_growth':
            kl_weight = 0.05 / (1 + np.exp(-2 * (epoch - 0.7 * num_epochs))) + 0.0005
        elif kl_schedule == 'sigmoid_decay':
            kl_weight = 0.05 / (1 + np.exp(2 * (epoch - 0.15 * num_epochs))) + 0.0005
        else:  # 'constant'
            kl_weight = 1.0

        running_train_loss = 0.0
        running_train_reconstruction_loss = 0.0
        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs, kl_loss = model(inputs)
            reconstruction_loss = reconstruction_loss_fn(outputs, targets)
            total_loss = reconstruction_loss + kl_weight * kl_loss
            total_loss.backward()
            optimizer.step()
            running_train_reconstruction_loss += reconstruction_loss.item()
            running_train_loss += total_loss.item()
        avg_train_loss = running_train_loss / len(train_loader)
        avg_train_reconstruction_loss = running_train_reconstruction_loss / len(train_loader)

        # --- Validation Loop ---
        model.eval()
        running_val_loss = 0.0
        running_val_reconstruction_loss = 0.0
        with torch.no_grad():
            for val_inputs, val_targets in val_loader:
                val_inputs, val_targets = val_inputs.to(device), val_targets.to(device)
                val_outputs, val_kl_loss = model(val_inputs)
                val_reconstruction_loss = reconstruction_loss_fn(val_outputs, val_targets)
                val_total_loss = val_reconstruction_loss + kl_weight * val_kl_loss
                running_val_reconstruction_loss += val_reconstruction_loss.item()
                running_val_loss += val_total_loss.item()
        avg_val_loss = running_val_loss / len(val_loader)
        avg_val_reconstruction_loss = running_val_reconstruction_loss / len(val_loader)

        print(f"Trial {trial.number}, Epoch {epoch+1}/{num_epochs}, "
              f"Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}, KL Weight: {kl_weight:.4f}, Train Recon. Loss: {avg_train_reconstruction_loss:.4f}, Val Recon. Loss: {avg_val_reconstruction_loss} ")

        # Report intermediate validation loss for pruning
        trial.report(avg_val_reconstruction_loss, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    # Return the final validation loss (the lower the better)
    return avg_val_reconstruction_loss

In [18]:
# --- Run the study ---
trials = 20
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=trials)  # Use n_jobs>1 with caution on GPU

# Print out the best results
print("Best trial:")
best_trial = study.best_trial
print("  Final Validation Loss (MAE): {:.4f}".format(best_trial.value))
print("  Params: ")
for key, value in best_trial.params.items():
    print("    {}: {}".format(key, value))
print()

trials_df = study.trials_dataframe()
print(trials_df)

[I 2025-02-16 21:02:50,371] A new study created in memory with name: no-name-3f19f279-0431-4572-8be3-4263e342ad2f
/tmp/ipykernel_3407211/2338334924.py:4: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  lr = trial.suggest_loguniform("lr", 1e-5, 1e-1)

Trial 0, Epoch 1/30, Train Loss: 0.4398, Val Loss: 0.3896, KL Weight: 0.0505, Train Recon. Loss: 0.1502, Val Recon. Loss: 0.10112757560469814
Trial 0, Epoch 2/30, Train Loss: 0.3900, Val Loss: 0.3834, KL Weight: 0.0505, Train Recon. Loss: 0.1029, Val Recon. Loss: 0.09725263719964358
Trial 0, Epoch 3/30, Train Loss: 0.3787, Val Loss: 0.3702, KL Weight: 0.0502, Train Recon. Loss: 0.0952, Val Recon. Loss: 0.08778599121358928
Trial 0, Epoch 4/30, Train Loss: 0.3473, Val Loss: 0.3326, KL Weight: 0.0481, Train Recon. Loss: 0.0773, Val Recon. Loss: 0.06343494339457324
Trial 0, Epoch 5/30, Train Loss: 0.2681, Val Loss: 0.2665, KL Weight: 0.0371, Train Recon. Loss: 0.0614, Val Recon. Loss: 0.06030451413383847
Trial 0, Epoch 6/30, Train Loss: 0.1367, Val Loss: 0.1355, KL Weight: 0.0139, Train Recon. Loss: 0.0591, Val Recon. Loss: 0.058067592152453086
Trial 0, Epoch 7/30, Train Loss: 0.0759, Val Loss: 0.0764, KL Weight: 0.0029, Train Recon. Loss: 0.0599, Val Recon. Loss: 0.060481997753574594
Trial 0, Epoch 8/30, Train Loss: 0.0627, Val Loss: 0.0624, KL Weight: 0.0008, Train Recon. Loss: 0.0581, Val Recon. Loss: 0.057716325266627934
Trial 0, Epoch 9/30, Train Loss: 0.0626, Val Loss: 0.0612, KL Weight: 0.0005, Train Recon. Loss: 0.0595, Val Recon. Loss: 0.058116737869218574
Trial 0, Epoch 10/30, Train Loss: 0.0590, Val Loss: 0.0587, KL Weight: 0.0005, Train Recon. Loss: 0.0562, Val Recon. Loss: 0.05583240569488064
Trial 0, Epoch 11/30, Train Loss: 0.0599, Val Loss: 0.0587, KL Weight: 0.0005, Train Recon. Loss: 0.0571, Val Recon. Loss: 0.05590247268461295
Trial 0, Epoch 12/30, Train Loss: 0.0591, Val Loss: 0.0563, KL Weight: 0.0005, Train Recon. Loss: 0.0563, Val Recon. Loss: 0.05350044117918848
Trial 0, Epoch 13/30, Train Loss: 0.0574, Val Loss: 0.0546, KL Weight: 0.0005, Train Recon. Loss: 0.0546, Val Recon. Loss: 0.051831547574310737
Trial 0, Epoch 14/30, Train Loss: 0.0547, Val Loss: 0.0525, KL Weight: 0.0005, Train Recon. Loss: 0.0519, Val Recon. Loss: 0.04966656659385777
Trial 0, Epoch 15/30, Train Loss: 0.0517, Val Loss: 0.0473, KL Weight: 0.0005, Train Recon. Loss: 0.0489, Val Recon. Loss: 0.04450541062790246
Trial 0, Epoch 16/30, Train Loss: 0.0434, Val Loss: 0.0354, KL Weight: 0.0005, Train Recon. Loss: 0.0406, Val Recon. Loss: 0.032574487854352546
Trial 0, Epoch 17/30, Train Loss: 0.0352, Val Loss: 0.0290, KL Weight: 0.0005, Train Recon. Loss: 0.0324, Val Recon. Loss: 0.026157963839177793
Trial 0, Epoch 18/30, Train Loss: 0.0315, Val Loss: 0.0271, KL Weight: 0.0005, Train Recon. Loss: 0.0287, Val Recon. Loss: 0.02423981254830867
Trial 0, Epoch 19/30, Train Loss: 0.0298, Val Loss: 0.0319, KL Weight: 0.0005, Train Recon. Loss: 0.0269, Val Recon. Loss: 0.0290978463311042
Trial 0, Epoch 20/30, Train Loss: 0.0287, Val Loss: 0.0276, KL Weight: 0.0005, Train Recon. Loss: 0.0258, Val Recon. Loss: 0.024711406016414677
Trial 0, Epoch 21/30, Train Loss: 0.0283, Val Loss: 0.0267, KL Weight: 0.0005, Train Recon. Loss: 0.0254, Val Recon. Loss: 0.023830164069562936
Trial 0, Epoch 22/30, Train Loss: 0.0267, Val Loss: 0.0270, KL Weight: 0.0005, Train Recon. Loss: 0.0238, Val Recon. Loss: 0.024189212769214007
Trial 0, Epoch 23/30, Train Loss: 0.0267, Val Loss: 0.0268, KL Weight: 0.0005, Train Recon. Loss: 0.0238, Val Recon. Loss: 0.023909475032083533
Trial 0, Epoch 24/30, Train Loss: 0.0257, Val Loss: 0.0258, KL Weight: 0.0005, Train Recon. Loss: 0.0228, Val Recon. Loss: 0.022923229571275256
Trial 0, Epoch 25/30, Train Loss: 0.0261, Val Loss: 0.0277, KL Weight: 0.0005, Train Recon. Loss: 0.0232, Val Recon. Loss: 0.024828892020094726
Trial 0, Epoch 26/30, Train Loss: 0.0256, Val Loss: 0.0236, KL Weight: 0.0005, Train Recon. Loss: 0.0227, Val Recon. Loss: 0.020701151670518895
Trial 0, Epoch 27/30, Train Loss: 0.0249, Val Loss: 0.0277, KL Weight: 0.0005, Train Recon. Loss: 0.0221, Val Recon. Loss: 0.02476642532036402
Trial 0, Epoch 28/30, Train Loss: 0.0248, Val Loss: 0.0235, KL Weight: 0.0005, Train Recon. Loss: 0.0219, Val Recon. Loss: 0.020612970058171375
Trial 0, Epoch 29/30, Train Loss: 0.0241, Val Loss: 0.0239, KL Weight: 0.0005, Train Recon. Loss: 0.0212, Val Recon. Loss: 0.021023937859698326

[I 2025-02-16 21:05:30,451] Trial 0 finished with value: 0.021199531543806934 and parameters: {'lr': 3.838611641997633e-05, 'batch_size': 512, 'hidden_size1': 80, 'hidden_size2': 16, 'hidden_size3': 24}. Best is trial 0 with value: 0.021199531543806934.

Trial 0, Epoch 30/30, Train Loss: 0.0228, Val Loss: 0.0241, KL Weight: 0.0005, Train Recon. Loss: 0.0199, Val Recon. Loss: 0.021199531543806934
Trial 1, Epoch 1/30, Train Loss: 0.2757, Val Loss: 0.2150, KL Weight: 0.0505, Train Recon. Loss: 0.1275, Val Recon. Loss: 0.1296699513323247
Trial 1, Epoch 2/30, Train Loss: 0.2105, Val Loss: 0.2010, KL Weight: 0.0505, Train Recon. Loss: 0.1400, Val Recon. Loss: 0.13694383123296652
Trial 1, Epoch 3/30, Train Loss: 0.2008, Val Loss: 0.1947, KL Weight: 0.0502, Train Recon. Loss: 0.1393, Val Recon. Loss: 0.13511208896790897
Trial 1, Epoch 4/30, Train Loss: 0.2001, Val Loss: 0.1937, KL Weight: 0.0481, Train Recon. Loss: 0.1405, Val Recon. Loss: 0.13148993617846622
Trial 1, Epoch 5/30, Train Loss: 0.1820, Val Loss: 0.1858, KL Weight: 0.0371, Train Recon. Loss: 0.1322, Val Recon. Loss: 0.13538980298303627
Trial 1, Epoch 6/30, Train Loss: 0.1482, Val Loss: 0.1480, KL Weight: 0.0139, Train Recon. Loss: 0.1252, Val Recon. Loss: 0.12088999596729248
Trial 1, Epoch 7/30, Train Loss: 0.1202, Val Loss: 0.1256, KL Weight: 0.0029, Train Recon. Loss: 0.1139, Val Recon. Loss: 0.11858493195952954
Trial 1, Epoch 8/30, Train Loss: 0.1170, Val Loss: 0.1268, KL Weight: 0.0008, Train Recon. Loss: 0.1148, Val Recon. Loss: 0.12449864608266421
Trial 1, Epoch 9/30, Train Loss: 0.1153, Val Loss: 0.1286, KL Weight: 0.0005, Train Recon. Loss: 0.1137, Val Recon. Loss: 0.12690118188457983
Trial 1, Epoch 10/30, Train Loss: 0.1143, Val Loss: 0.1286, KL Weight: 0.0005, Train Recon. Loss: 0.1127, Val Recon. Loss: 0.12697191249478507
Trial 1, Epoch 11/30, Train Loss: 0.1139, Val Loss: 0.1251, KL Weight: 0.0005, Train Recon. Loss: 0.1123, Val Recon. Loss: 0.12342542258312215
Trial 1, Epoch 12/30, Train Loss: 0.1143, Val Loss: 0.1218, KL Weight: 0.0005, Train Recon. Loss: 0.1126, Val Recon. Loss: 0.12007221953199432
Trial 1, Epoch 13/30, Train Loss: 0.1142, Val Loss: 0.1260, KL Weight: 0.0005, Train Recon. Loss: 0.1125, Val Recon. Loss: 0.1242334911342453
Trial 1, Epoch 14/30, Train Loss: 0.1142, Val Loss: 0.1262, KL Weight: 0.0005, Train Recon. Loss: 0.1124, Val Recon. Loss: 0.12439690573370313
Trial 1, Epoch 15/30, Train Loss: 0.1142, Val Loss: 0.1237, KL Weight: 0.0005, Train Recon. Loss: 0.1124, Val Recon. Loss: 0.12188869404296081
Trial 1, Epoch 16/30, Train Loss: 0.1140, Val Loss: 0.1257, KL Weight: 0.0005, Train Recon. Loss: 0.1122, Val Recon. Loss: 0.12382855446164583
Trial 1, Epoch 17/30, Train Loss: 0.1139, Val Loss: 0.1264, KL Weight: 0.0005, Train Recon. Loss: 0.1121, Val Recon. Loss: 0.12450912874471676
Trial 1, Epoch 18/30, Train Loss: 0.1151, Val Loss: 0.1248, KL Weight: 0.0005, Train Recon. Loss: 0.1132, Val Recon. Loss: 0.12295423909551925
Trial 1, Epoch 19/30, Train Loss: 0.1141, Val Loss: 0.1244, KL Weight: 0.0005, Train Recon. Loss: 0.1122, Val Recon. Loss: 0.12258892682836847
Trial 1, Epoch 20/30, Train Loss: 0.1146, Val Loss: 0.1228, KL Weight: 0.0005, Train Recon. Loss: 0.1127, Val Recon. Loss: 0.12096257831107031
Trial 1, Epoch 21/30, Train Loss: 0.1141, Val Loss: 0.1278, KL Weight: 0.0005, Train Recon. Loss: 0.1123, Val Recon. Loss: 0.12600347467952663
Trial 1, Epoch 22/30, Train Loss: 0.1145, Val Loss: 0.1274, KL Weight: 0.0005, Train Recon. Loss: 0.1127, Val Recon. Loss: 0.1255805001736761
Trial 1, Epoch 23/30, Train Loss: 0.1140, Val Loss: 0.1235, KL Weight: 0.0005, Train Recon. Loss: 0.1122, Val Recon. Loss: 0.1217635632170974
Trial 1, Epoch 24/30, Train Loss: 0.1144, Val Loss: 0.1251, KL Weight: 0.0005, Train Recon. Loss: 0.1126, Val Recon. Loss: 0.12332219378211656
Trial 1, Epoch 25/30, Train Loss: 0.1137, Val Loss: 0.1231, KL Weight: 0.0005, Train Recon. Loss: 0.1119, Val Recon. Loss: 0.12133682829917998
Trial 1, Epoch 26/30, Train Loss: 0.1144, Val Loss: 0.1264, KL Weight: 0.0005, Train Recon. Loss: 0.1126, Val Recon. Loss: 0.12461181216546006
Trial 1, Epoch 27/30, Train Loss: 0.1142, Val Loss: 0.1265, KL Weight: 0.0005, Train Recon. Loss: 0.1124, Val Recon. Loss: 0.12467017633611108
Trial 1, Epoch 28/30, Train Loss: 0.1143, Val Loss: 0.1234, KL Weight: 0.0005, Train Recon. Loss: 0.1124, Val Recon. Loss: 0.12152900726061773
Trial 1, Epoch 29/30, Train Loss: 0.1135, Val Loss: 0.1254, KL Weight: 0.0005, Train Recon. Loss: 0.1116, Val Recon. Loss: 0.12350390096371239

[I 2025-02-16 21:08:12,699] Trial 1 finished with value: 0.12264742959827722 and parameters: {'lr': 0.008297299238221282, 'batch_size': 512, 'hidden_size1': 64, 'hidden_size2': 112, 'hidden_size3': 64}. Best is trial 0 with value: 0.021199531543806934.

Trial 1, Epoch 30/30, Train Loss: 0.1144, Val Loss: 0.1245, KL Weight: 0.0005, Train Recon. Loss: 0.1126, Val Recon. Loss: 0.12264742959827722
Trial 2, Epoch 1/30, Train Loss: 0.2875, Val Loss: 0.2291, KL Weight: 0.0505, Train Recon. Loss: 0.1163, Val Recon. Loss: 0.12931857518501635
Trial 2, Epoch 2/30, Train Loss: 0.2103, Val Loss: 0.1982, KL Weight: 0.0505, Train Recon. Loss: 0.1325, Val Recon. Loss: 0.13252200993072044
Trial 2, Epoch 3/30, Train Loss: 0.1995, Val Loss: 0.1919, KL Weight: 0.0502, Train Recon. Loss: 0.1359, Val Recon. Loss: 0.12699374232959365
Trial 2, Epoch 4/30, Train Loss: 0.1968, Val Loss: 0.2310, KL Weight: 0.0481, Train Recon. Loss: 0.1368, Val Recon. Loss: 0.16964334776008824
Trial 2, Epoch 5/30, Train Loss: 0.1804, Val Loss: 0.1730, KL Weight: 0.0371, Train Recon. Loss: 0.1302, Val Recon. Loss: 0.1213358220525254
Trial 2, Epoch 6/30, Train Loss: 0.1418, Val Loss: 0.1428, KL Weight: 0.0139, Train Recon. Loss: 0.1180, Val Recon. Loss: 0.11594100714472115
Trial 2, Epoch 7/30, Train Loss: 0.1172, Val Loss: 0.2244, KL Weight: 0.0029, Train Recon. Loss: 0.1110, Val Recon. Loss: 0.2174973727757097
Trial 2, Epoch 8/30, Train Loss: 0.1113, Val Loss: 0.1170, KL Weight: 0.0008, Train Recon. Loss: 0.1090, Val Recon. Loss: 0.11455239342504595
Trial 2, Epoch 9/30, Train Loss: 0.1085, Val Loss: 0.1140, KL Weight: 0.0005, Train Recon. Loss: 0.1068, Val Recon. Loss: 0.11221051465411831
Trial 2, Epoch 10/30, Train Loss: 0.1079, Val Loss: 0.1139, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.11215173943192328
Trial 2, Epoch 11/30, Train Loss: 0.1072, Val Loss: 0.1148, KL Weight: 0.0005, Train Recon. Loss: 0.1054, Val Recon. Loss: 0.11299847645222917
Trial 2, Epoch 12/30, Train Loss: 0.1074, Val Loss: 0.1138, KL Weight: 0.0005, Train Recon. Loss: 0.1056, Val Recon. Loss: 0.11193478563380309
Trial 2, Epoch 13/30, Train Loss: 0.1077, Val Loss: 0.1135, KL Weight: 0.0005, Train Recon. Loss: 0.1059, Val Recon. Loss: 0.11169623785785267
Trial 2, Epoch 14/30, Train Loss: 0.1075, Val Loss: 0.1137, KL Weight: 0.0005, Train Recon. Loss: 0.1057, Val Recon. Loss: 0.1118178911051972
Trial 2, Epoch 15/30, Train Loss: 0.1076, Val Loss: 0.1143, KL Weight: 0.0005, Train Recon. Loss: 0.1058, Val Recon. Loss: 0.11242812547300543
Trial 2, Epoch 16/30, Train Loss: 0.1078, Val Loss: 0.1148, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11295790478160003
Trial 2, Epoch 17/30, Train Loss: 0.1074, Val Loss: 0.1142, KL Weight: 0.0005, Train Recon. Loss: 0.1056, Val Recon. Loss: 0.11240315487664333
Trial 2, Epoch 18/30, Train Loss: 0.1078, Val Loss: 0.1139, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11207735548286062
Trial 2, Epoch 19/30, Train Loss: 0.1077, Val Loss: 0.1147, KL Weight: 0.0005, Train Recon. Loss: 0.1059, Val Recon. Loss: 0.11281308962620402
Trial 2, Epoch 20/30, Train Loss: 0.1078, Val Loss: 0.1147, KL Weight: 0.0005, Train Recon. Loss: 0.1059, Val Recon. Loss: 0.11283611723929084
Trial 2, Epoch 21/30, Train Loss: 0.1077, Val Loss: 0.1146, KL Weight: 0.0005, Train Recon. Loss: 0.1058, Val Recon. Loss: 0.11269073737995293
Trial 2, Epoch 22/30, Train Loss: 0.1079, Val Loss: 0.1136, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11166662137073122
Trial 2, Epoch 23/30, Train Loss: 0.1074, Val Loss: 0.1138, KL Weight: 0.0005, Train Recon. Loss: 0.1055, Val Recon. Loss: 0.11186452389421656
Trial 2, Epoch 24/30, Train Loss: 0.1063, Val Loss: 0.1145, KL Weight: 0.0005, Train Recon. Loss: 0.1044, Val Recon. Loss: 0.11259629861486697
Trial 2, Epoch 25/30, Train Loss: 0.1079, Val Loss: 0.1145, KL Weight: 0.0005, Train Recon. Loss: 0.1059, Val Recon. Loss: 0.11252743826086696
Trial 2, Epoch 26/30, Train Loss: 0.1076, Val Loss: 0.1159, KL Weight: 0.0005, Train Recon. Loss: 0.1057, Val Recon. Loss: 0.11403936837988912
Trial 2, Epoch 27/30, Train Loss: 0.1075, Val Loss: 0.1132, KL Weight: 0.0005, Train Recon. Loss: 0.1056, Val Recon. Loss: 0.1113198521455988
Trial 2, Epoch 28/30, Train Loss: 0.1080, Val Loss: 0.1154, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11341805109768209
Trial 2, Epoch 29/30, Train Loss: 0.1073, Val Loss: 0.1152, KL Weight: 0.0005, Train Recon. Loss: 0.1053, Val Recon. Loss: 0.1132803405109877

[I 2025-02-16 21:12:16,578] Trial 2 finished with value: 0.1129083200168789 and parameters: {'lr': 0.003007854470842445, 'batch_size': 256, 'hidden_size1': 64, 'hidden_size2': 112, 'hidden_size3': 64}. Best is trial 0 with value: 0.021199531543806934.

Trial 2, Epoch 30/30, Train Loss: 0.1076, Val Loss: 0.1148, KL Weight: 0.0005, Train Recon. Loss: 0.1058, Val Recon. Loss: 0.1129083200168789
Trial 3, Epoch 1/30, Train Loss: 0.5148, Val Loss: 0.4422, KL Weight: 0.0505, Train Recon. Loss: 0.2240, Val Recon. Loss: 0.15175674683428383
Trial 3, Epoch 2/30, Train Loss: 0.4009, Val Loss: 0.3939, KL Weight: 0.0505, Train Recon. Loss: 0.1109, Val Recon. Loss: 0.10419616663084552
Trial 3, Epoch 3/30, Train Loss: 0.3931, Val Loss: 0.3899, KL Weight: 0.0502, Train Recon. Loss: 0.1054, Val Recon. Loss: 0.10249409075496388
Trial 3, Epoch 4/30, Train Loss: 0.3810, Val Loss: 0.3782, KL Weight: 0.0481, Train Recon. Loss: 0.1055, Val Recon. Loss: 0.10299786718914637
Trial 3, Epoch 5/30, Train Loss: 0.3167, Val Loss: 0.3128, KL Weight: 0.0371, Train Recon. Loss: 0.1050, Val Recon. Loss: 0.1012139768666915
Trial 3, Epoch 6/30, Train Loss: 0.1831, Val Loss: 0.1813, KL Weight: 0.0139, Train Recon. Loss: 0.1035, Val Recon. Loss: 0.10175762961789205
Trial 3, Epoch 7/30, Train Loss: 0.1194, Val Loss: 0.1148, KL Weight: 0.0029, Train Recon. Loss: 0.1030, Val Recon. Loss: 0.09840703824417549
Trial 3, Epoch 8/30, Train Loss: 0.1078, Val Loss: 0.1024, KL Weight: 0.0008, Train Recon. Loss: 0.1030, Val Recon. Loss: 0.09768337741572489
Trial 3, Epoch 9/30, Train Loss: 0.1046, Val Loss: 0.1004, KL Weight: 0.0005, Train Recon. Loss: 0.1015, Val Recon. Loss: 0.09732048201455816
Trial 3, Epoch 10/30, Train Loss: 0.1031, Val Loss: 0.1006, KL Weight: 0.0005, Train Recon. Loss: 0.1002, Val Recon. Loss: 0.09769226762245188
Trial 3, Epoch 11/30, Train Loss: 0.1028, Val Loss: 0.0972, KL Weight: 0.0005, Train Recon. Loss: 0.0999, Val Recon. Loss: 0.09431884753554165
Trial 3, Epoch 12/30, Train Loss: 0.1000, Val Loss: 0.0970, KL Weight: 0.0005, Train Recon. Loss: 0.0972, Val Recon. Loss: 0.09415980916038189
Trial 3, Epoch 13/30, Train Loss: 0.0989, Val Loss: 0.0928, KL Weight: 0.0005, Train Recon. Loss: 0.0961, Val Recon. Loss: 0.08989984863899178
Trial 3, Epoch 14/30, Train Loss: 0.0973, Val Loss: 0.0915, KL Weight: 0.0005, Train Recon. Loss: 0.0944, Val Recon. Loss: 0.08862629903105644
Trial 3, Epoch 15/30, Train Loss: 0.0947, Val Loss: 0.0883, KL Weight: 0.0005, Train Recon. Loss: 0.0918, Val Recon. Loss: 0.08544371066917036
Trial 3, Epoch 16/30, Train Loss: 0.0908, Val Loss: 0.0831, KL Weight: 0.0005, Train Recon. Loss: 0.0880, Val Recon. Loss: 0.0802082909318666
Trial 3, Epoch 17/30, Train Loss: 0.0864, Val Loss: 0.0810, KL Weight: 0.0005, Train Recon. Loss: 0.0836, Val Recon. Loss: 0.07816987121673497
Trial 3, Epoch 18/30, Train Loss: 0.0833, Val Loss: 0.0776, KL Weight: 0.0005, Train Recon. Loss: 0.0804, Val Recon. Loss: 0.0747390125043321
Trial 3, Epoch 19/30, Train Loss: 0.0795, Val Loss: 0.0748, KL Weight: 0.0005, Train Recon. Loss: 0.0767, Val Recon. Loss: 0.07189385463901748
Trial 3, Epoch 20/30, Train Loss: 0.0764, Val Loss: 0.0728, KL Weight: 0.0005, Train Recon. Loss: 0.0735, Val Recon. Loss: 0.06995458705015145
Trial 3, Epoch 21/30, Train Loss: 0.0744, Val Loss: 0.0701, KL Weight: 0.0005, Train Recon. Loss: 0.0715, Val Recon. Loss: 0.06726295615591153
Trial 3, Epoch 22/30, Train Loss: 0.0741, Val Loss: 0.0713, KL Weight: 0.0005, Train Recon. Loss: 0.0712, Val Recon. Loss: 0.06842041881293529
Trial 3, Epoch 23/30, Train Loss: 0.0723, Val Loss: 0.0725, KL Weight: 0.0005, Train Recon. Loss: 0.0695, Val Recon. Loss: 0.06965792529682095
Trial 3, Epoch 24/30, Train Loss: 0.0719, Val Loss: 0.0701, KL Weight: 0.0005, Train Recon. Loss: 0.0690, Val Recon. Loss: 0.06723196367668854
Trial 3, Epoch 25/30, Train Loss: 0.0709, Val Loss: 0.0708, KL Weight: 0.0005, Train Recon. Loss: 0.0681, Val Recon. Loss: 0.06793081167737139
Trial 3, Epoch 26/30, Train Loss: 0.0711, Val Loss: 0.0704, KL Weight: 0.0005, Train Recon. Loss: 0.0682, Val Recon. Loss: 0.06750044552015012
Trial 3, Epoch 27/30, Train Loss: 0.0694, Val Loss: 0.0693, KL Weight: 0.0005, Train Recon. Loss: 0.0666, Val Recon. Loss: 0.06640994725273447
Trial 3, Epoch 28/30, Train Loss: 0.0689, Val Loss: 0.0685, KL Weight: 0.0005, Train Recon. Loss: 0.0661, Val Recon. Loss: 0.06563398231229221
Trial 3, Epoch 29/30, Train Loss: 0.0678, Val Loss: 0.0668, KL Weight: 0.0005, Train Recon. Loss: 0.0649, Val Recon. Loss: 0.06396599611765272

[I 2025-02-16 21:14:53,832] Trial 3 finished with value: 0.06428661585195332 and parameters: {'lr': 1.05333493255141e-05, 'batch_size': 512, 'hidden_size1': 32, 'hidden_size2': 64, 'hidden_size3': 40}. Best is trial 0 with value: 0.021199531543806934.

Trial 3, Epoch 30/30, Train Loss: 0.0675, Val Loss: 0.0672, KL Weight: 0.0005, Train Recon. Loss: 0.0646, Val Recon. Loss: 0.06428661585195332
Trial 4, Epoch 1/30, Train Loss: 0.2690, Val Loss: 0.2117, KL Weight: 0.0505, Train Recon. Loss: 0.1197, Val Recon. Loss: 0.13522053400432704
Trial 4, Epoch 2/30, Train Loss: 0.2043, Val Loss: 0.1912, KL Weight: 0.0505, Train Recon. Loss: 0.1380, Val Recon. Loss: 0.1258769040367097
Trial 4, Epoch 3/30, Train Loss: 0.1964, Val Loss: 0.1947, KL Weight: 0.0502, Train Recon. Loss: 0.1339, Val Recon. Loss: 0.13548496469113053
Trial 4, Epoch 4/30, Train Loss: 0.1927, Val Loss: 0.1899, KL Weight: 0.0481, Train Recon. Loss: 0.1342, Val Recon. Loss: 0.13100698566400354
Trial 4, Epoch 5/30, Train Loss: 0.1772, Val Loss: 0.1745, KL Weight: 0.0371, Train Recon. Loss: 0.1282, Val Recon. Loss: 0.12348629276275186
Trial 4, Epoch 6/30, Train Loss: 0.1427, Val Loss: 0.1434, KL Weight: 0.0139, Train Recon. Loss: 0.1187, Val Recon. Loss: 0.11572321238122264
Trial 4, Epoch 7/30, Train Loss: 0.1171, Val Loss: 0.1183, KL Weight: 0.0029, Train Recon. Loss: 0.1105, Val Recon. Loss: 0.1108489570211395
Trial 4, Epoch 8/30, Train Loss: 0.1097, Val Loss: 0.1181, KL Weight: 0.0008, Train Recon. Loss: 0.1074, Val Recon. Loss: 0.11562544604819408
Trial 4, Epoch 9/30, Train Loss: 0.1081, Val Loss: 0.1168, KL Weight: 0.0005, Train Recon. Loss: 0.1064, Val Recon. Loss: 0.11505018146568559
Trial 4, Epoch 10/30, Train Loss: 0.1082, Val Loss: 0.1153, KL Weight: 0.0005, Train Recon. Loss: 0.1065, Val Recon. Loss: 0.1135532760957634
Trial 4, Epoch 11/30, Train Loss: 0.1083, Val Loss: 0.1154, KL Weight: 0.0005, Train Recon. Loss: 0.1065, Val Recon. Loss: 0.11360461081630249
Trial 4, Epoch 12/30, Train Loss: 0.1084, Val Loss: 0.1140, KL Weight: 0.0005, Train Recon. Loss: 0.1066, Val Recon. Loss: 0.11210813804816706
Trial 4, Epoch 13/30, Train Loss: 0.1076, Val Loss: 0.1176, KL Weight: 0.0005, Train Recon. Loss: 0.1057, Val Recon. Loss: 0.11573058127852759
Trial 4, Epoch 14/30, Train Loss: 0.1079, Val Loss: 0.1168, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11493974606317461
Trial 4, Epoch 15/30, Train Loss: 0.1081, Val Loss: 0.1175, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.11564190808046414
Trial 4, Epoch 16/30, Train Loss: 0.1082, Val Loss: 0.1167, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.1147128128880789
Trial 4, Epoch 17/30, Train Loss: 0.1081, Val Loss: 0.1176, KL Weight: 0.0005, Train Recon. Loss: 0.1061, Val Recon. Loss: 0.11565738024008006
Trial 4, Epoch 18/30, Train Loss: 0.1079, Val Loss: 0.1170, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11515684482760559
Trial 4, Epoch 19/30, Train Loss: 0.1080, Val Loss: 0.1161, KL Weight: 0.0005, Train Recon. Loss: 0.1061, Val Recon. Loss: 0.11418707759777798
Trial 4, Epoch 20/30, Train Loss: 0.1078, Val Loss: 0.1171, KL Weight: 0.0005, Train Recon. Loss: 0.1059, Val Recon. Loss: 0.11518286711753423
Trial 4, Epoch 21/30, Train Loss: 0.1081, Val Loss: 0.1163, KL Weight: 0.0005, Train Recon. Loss: 0.1062, Val Recon. Loss: 0.11439294633980757
Trial 4, Epoch 22/30, Train Loss: 0.1081, Val Loss: 0.1173, KL Weight: 0.0005, Train Recon. Loss: 0.1062, Val Recon. Loss: 0.11545503474351831
Trial 4, Epoch 23/30, Train Loss: 0.1080, Val Loss: 0.1169, KL Weight: 0.0005, Train Recon. Loss: 0.1062, Val Recon. Loss: 0.11497679284836788
Trial 4, Epoch 24/30, Train Loss: 0.1078, Val Loss: 0.1152, KL Weight: 0.0005, Train Recon. Loss: 0.1060, Val Recon. Loss: 0.11333131781408101
Trial 4, Epoch 25/30, Train Loss: 0.1082, Val Loss: 0.1171, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.11523504324705529
Trial 4, Epoch 26/30, Train Loss: 0.1082, Val Loss: 0.1152, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.11325706768696918
Trial 4, Epoch 27/30, Train Loss: 0.1080, Val Loss: 0.1171, KL Weight: 0.0005, Train Recon. Loss: 0.1061, Val Recon. Loss: 0.11515282129070588
Trial 4, Epoch 28/30, Train Loss: 0.1081, Val Loss: 0.1165, KL Weight: 0.0005, Train Recon. Loss: 0.1062, Val Recon. Loss: 0.11462744658854895
Trial 4, Epoch 29/30, Train Loss: 0.1085, Val Loss: 0.1160, KL Weight: 0.0005, Train Recon. Loss: 0.1067, Val Recon. Loss: 0.11403333232072847

[I 2025-02-16 21:18:49,156] Trial 4 finished with value: 0.11638219946421179 and parameters: {'lr': 0.003726336098597104, 'batch_size': 256, 'hidden_size1': 128, 'hidden_size2': 112, 'hidden_size3': 48}. Best is trial 0 with value: 0.021199531543806934.

Trial 4, Epoch 30/30, Train Loss: 0.1082, Val Loss: 0.1183, KL Weight: 0.0005, Train Recon. Loss: 0.1063, Val Recon. Loss: 0.11638219946421179
Trial 5, Epoch 1/30, Train Loss: 0.3736, Val Loss: 0.3519, KL Weight: 0.0505, Train Recon. Loss: 0.1042, Val Recon. Loss: 0.0941700355286847
Trial 5, Epoch 2/30, Train Loss: 0.3202, Val Loss: 0.3075, KL Weight: 0.0505, Train Recon. Loss: 0.0736, Val Recon. Loss: 0.07146186909048229
Trial 5, Epoch 3/30, Train Loss: 0.2821, Val Loss: 0.2686, KL Weight: 0.0502, Train Recon. Loss: 0.0569, Val Recon. Loss: 0.05235222935279434
Trial 5, Epoch 4/30, Train Loss: 0.2509, Val Loss: 0.2475, KL Weight: 0.0481, Train Recon. Loss: 0.0509, Val Recon. Loss: 0.054675023071467876
Trial 5, Epoch 5/30, Train Loss: 0.1968, Val Loss: 0.1929, KL Weight: 0.0371, Train Recon. Loss: 0.0515, Val Recon. Loss: 0.05055819442859283
Trial 5, Epoch 6/30, Train Loss: 0.0991, Val Loss: 0.0993, KL Weight: 0.0139, Train Recon. Loss: 0.0449, Val Recon. Loss: 0.04470952932679866
Trial 5, Epoch 7/30, Train Loss: 0.0537, Val Loss: 0.0650, KL Weight: 0.0029, Train Recon. Loss: 0.0422, Val Recon. Loss: 0.053273323445102654
Trial 5, Epoch 8/30, Train Loss: 0.0415, Val Loss: 0.0535, KL Weight: 0.0008, Train Recon. Loss: 0.0380, Val Recon. Loss: 0.04999707461482993
Trial 5, Epoch 9/30, Train Loss: 0.0372, Val Loss: 0.0418, KL Weight: 0.0005, Train Recon. Loss: 0.0348, Val Recon. Loss: 0.03936442786893407
Trial 5, Epoch 10/30, Train Loss: 0.0351, Val Loss: 0.0417, KL Weight: 0.0005, Train Recon. Loss: 0.0328, Val Recon. Loss: 0.03942911740876287
Trial 5, Epoch 11/30, Train Loss: 0.0300, Val Loss: 0.0394, KL Weight: 0.0005, Train Recon. Loss: 0.0277, Val Recon. Loss: 0.037060295990961896
Trial 5, Epoch 12/30, Train Loss: 0.0274, Val Loss: 0.0342, KL Weight: 0.0005, Train Recon. Loss: 0.0250, Val Recon. Loss: 0.031817730861595714
Trial 5, Epoch 13/30, Train Loss: 0.0251, Val Loss: 0.0348, KL Weight: 0.0005, Train Recon. Loss: 0.0226, Val Recon. Loss: 0.032274573111442384
Trial 5, Epoch 14/30, Train Loss: 0.0246, Val Loss: 0.0304, KL Weight: 0.0005, Train Recon. Loss: 0.0221, Val Recon. Loss: 0.027850590264508583
Trial 5, Epoch 15/30, Train Loss: 0.0233, Val Loss: 0.0384, KL Weight: 0.0005, Train Recon. Loss: 0.0208, Val Recon. Loss: 0.03576162464737713
Trial 5, Epoch 16/30, Train Loss: 0.0221, Val Loss: 0.0336, KL Weight: 0.0005, Train Recon. Loss: 0.0194, Val Recon. Loss: 0.030980368023150944
Trial 5, Epoch 17/30, Train Loss: 0.0234, Val Loss: 0.0352, KL Weight: 0.0005, Train Recon. Loss: 0.0207, Val Recon. Loss: 0.032494396816095894
Trial 5, Epoch 18/30, Train Loss: 0.0198, Val Loss: 0.0215, KL Weight: 0.0005, Train Recon. Loss: 0.0170, Val Recon. Loss: 0.01872020539605302
Trial 5, Epoch 19/30, Train Loss: 0.0218, Val Loss: 0.0367, KL Weight: 0.0005, Train Recon. Loss: 0.0190, Val Recon. Loss: 0.033939329354937105
Trial 5, Epoch 20/30, Train Loss: 0.0194, Val Loss: 0.0254, KL Weight: 0.0005, Train Recon. Loss: 0.0165, Val Recon. Loss: 0.02251671752319098
Trial 5, Epoch 21/30, Train Loss: 0.0169, Val Loss: 0.0299, KL Weight: 0.0005, Train Recon. Loss: 0.0140, Val Recon. Loss: 0.02700806202579502
Trial 5, Epoch 22/30, Train Loss: 0.0167, Val Loss: 0.0246, KL Weight: 0.0005, Train Recon. Loss: 0.0138, Val Recon. Loss: 0.021671568985165632
Trial 5, Epoch 23/30, Train Loss: 0.0175, Val Loss: 0.0296, KL Weight: 0.0005, Train Recon. Loss: 0.0145, Val Recon. Loss: 0.026603677984069776
Trial 5, Epoch 24/30, Train Loss: 0.0156, Val Loss: 0.0269, KL Weight: 0.0005, Train Recon. Loss: 0.0126, Val Recon. Loss: 0.02386546184031947
Trial 5, Epoch 25/30, Train Loss: 0.0167, Val Loss: 0.0284, KL Weight: 0.0005, Train Recon. Loss: 0.0137, Val Recon. Loss: 0.025322948147573538
Trial 5, Epoch 26/30, Train Loss: 0.0159, Val Loss: 0.0223, KL Weight: 0.0005, Train Recon. Loss: 0.0128, Val Recon. Loss: 0.019201362618124922
Trial 5, Epoch 27/30, Train Loss: 0.0153, Val Loss: 0.0235, KL Weight: 0.0005, Train Recon. Loss: 0.0122, Val Recon. Loss: 0.02037940337899485
Trial 5, Epoch 28/30, Train Loss: 0.0146, Val Loss: 0.0283, KL Weight: 0.0005, Train Recon. Loss: 0.0114, Val Recon. Loss: 0.02515288137805623
Trial 5, Epoch 29/30, Train Loss: 0.0155, Val Loss: 0.0300, KL Weight: 0.0005, Train Recon. Loss: 0.0123, Val Recon. Loss: 0.02674746887713626

[I 2025-02-16 21:21:25,610] Trial 5 finished with value: 0.017414332954101153 and parameters: {'lr': 0.0004465210528486487, 'batch_size': 512, 'hidden_size1': 48, 'hidden_size2': 80, 'hidden_size3': 24}. Best is trial 5 with value: 0.017414332954101153.

Trial 5, Epoch 30/30, Train Loss: 0.0148, Val Loss: 0.0207, KL Weight: 0.0005, Train Recon. Loss: 0.0115, Val Recon. Loss: 0.017414332954101153
Trial 6, Epoch 1/30, Train Loss: 0.3942, Val Loss: 0.3850, KL Weight: 0.0505, Train Recon. Loss: 0.1101, Val Recon. Loss: 0.1018234244197663
Trial 6, Epoch 2/30, Train Loss: 0.3855, Val Loss: 0.3791, KL Weight: 0.0505, Train Recon. Loss: 0.1035, Val Recon. Loss: 0.09806490162233437
Trial 6, Epoch 3/30, Train Loss: 0.3749, Val Loss: 0.3667, KL Weight: 0.0502, Train Recon. Loss: 0.0964, Val Recon. Loss: 0.08919249695018494
Trial 6, Epoch 4/30, Train Loss: 0.3428, Val Loss: 0.3265, KL Weight: 0.0481, Train Recon. Loss: 0.0775, Val Recon. Loss: 0.06200590632379727
Trial 6, Epoch 5/30, Train Loss: 0.2535, Val Loss: 0.2491, KL Weight: 0.0371, Train Recon. Loss: 0.0503, Val Recon. Loss: 0.04645649983137986
Trial 6, Epoch 6/30, Train Loss: 0.1069, Val Loss: 0.1119, KL Weight: 0.0139, Train Recon. Loss: 0.0306, Val Recon. Loss: 0.03570205864839648
Trial 6, Epoch 7/30, Train Loss: 0.0431, Val Loss: 0.0472, KL Weight: 0.0029, Train Recon. Loss: 0.0274, Val Recon. Loss: 0.03145639286096439
Trial 6, Epoch 8/30, Train Loss: 0.0302, Val Loss: 0.0374, KL Weight: 0.0008, Train Recon. Loss: 0.0256, Val Recon. Loss: 0.0328090998123547
Trial 6, Epoch 9/30, Train Loss: 0.0276, Val Loss: 0.0292, KL Weight: 0.0005, Train Recon. Loss: 0.0246, Val Recon. Loss: 0.02620859783864055
Trial 6, Epoch 10/30, Train Loss: 0.0267, Val Loss: 0.0292, KL Weight: 0.0005, Train Recon. Loss: 0.0239, Val Recon. Loss: 0.02642928261950584
Trial 6, Epoch 11/30, Train Loss: 0.0268, Val Loss: 0.0258, KL Weight: 0.0005, Train Recon. Loss: 0.0240, Val Recon. Loss: 0.023033227804782137
Trial 6, Epoch 12/30, Train Loss: 0.0256, Val Loss: 0.0287, KL Weight: 0.0005, Train Recon. Loss: 0.0229, Val Recon. Loss: 0.02594101754423315
Trial 6, Epoch 13/30, Train Loss: 0.0258, Val Loss: 0.0279, KL Weight: 0.0005, Train Recon. Loss: 0.0230, Val Recon. Loss: 0.02514582971159957
Trial 6, Epoch 14/30, Train Loss: 0.0251, Val Loss: 0.0281, KL Weight: 0.0005, Train Recon. Loss: 0.0223, Val Recon. Loss: 0.025339116390157294
Trial 6, Epoch 15/30, Train Loss: 0.0245, Val Loss: 0.0249, KL Weight: 0.0005, Train Recon. Loss: 0.0218, Val Recon. Loss: 0.02216122982361795
Trial 6, Epoch 16/30, Train Loss: 0.0245, Val Loss: 0.0258, KL Weight: 0.0005, Train Recon. Loss: 0.0217, Val Recon. Loss: 0.02300747584786154
Trial 6, Epoch 17/30, Train Loss: 0.0241, Val Loss: 0.0228, KL Weight: 0.0005, Train Recon. Loss: 0.0213, Val Recon. Loss: 0.019986665088515307
Trial 6, Epoch 18/30, Train Loss: 0.0237, Val Loss: 0.0236, KL Weight: 0.0005, Train Recon. Loss: 0.0209, Val Recon. Loss: 0.020799866933340586
Trial 6, Epoch 19/30, Train Loss: 0.0239, Val Loss: 0.0224, KL Weight: 0.0005, Train Recon. Loss: 0.0211, Val Recon. Loss: 0.019579154417037795
Trial 6, Epoch 20/30, Train Loss: 0.0231, Val Loss: 0.0223, KL Weight: 0.0005, Train Recon. Loss: 0.0203, Val Recon. Loss: 0.019510914985776732
Trial 6, Epoch 21/30, Train Loss: 0.0234, Val Loss: 0.0227, KL Weight: 0.0005, Train Recon. Loss: 0.0206, Val Recon. Loss: 0.01990083288830264
Trial 6, Epoch 22/30, Train Loss: 0.0227, Val Loss: 0.0264, KL Weight: 0.0005, Train Recon. Loss: 0.0199, Val Recon. Loss: 0.023603963346003478
Trial 6, Epoch 23/30, Train Loss: 0.0223, Val Loss: 0.0233, KL Weight: 0.0005, Train Recon. Loss: 0.0195, Val Recon. Loss: 0.02042599892492329
Trial 6, Epoch 24/30, Train Loss: 0.0218, Val Loss: 0.0219, KL Weight: 0.0005, Train Recon. Loss: 0.0190, Val Recon. Loss: 0.018999310946914795
Trial 6, Epoch 25/30, Train Loss: 0.0213, Val Loss: 0.0255, KL Weight: 0.0005, Train Recon. Loss: 0.0185, Val Recon. Loss: 0.02263427095687283
Trial 6, Epoch 26/30, Train Loss: 0.0218, Val Loss: 0.0214, KL Weight: 0.0005, Train Recon. Loss: 0.0189, Val Recon. Loss: 0.018574386796935047
Trial 6, Epoch 27/30, Train Loss: 0.0210, Val Loss: 0.0224, KL Weight: 0.0005, Train Recon. Loss: 0.0181, Val Recon. Loss: 0.019501584541591767
Trial 6, Epoch 28/30, Train Loss: 0.0210, Val Loss: 0.0223, KL Weight: 0.0005, Train Recon. Loss: 0.0181, Val Recon. Loss: 0.019382454392927368
Trial 6, Epoch 29/30, Train Loss: 0.0211, Val Loss: 0.0238, KL Weight: 0.0005, Train Recon. Loss: 0.0182, Val Recon. Loss: 0.02094545853709368

[I 2025-02-16 21:25:21,128] Trial 6 finished with value: 0.018771202028974105 and parameters: {'lr': 1.644460098232641e-05, 'batch_size': 256, 'hidden_size1': 96, 'hidden_size2': 128, 'hidden_size3': 16}. Best is trial 5 with value: 0.017414332954101153.

Trial 6, Epoch 30/30, Train Loss: 0.0203, Val Loss: 0.0217, KL Weight: 0.0005, Train Recon. Loss: 0.0174, Val Recon. Loss: 0.018771202028974105

[I 2025-02-16 21:25:28,984] Trial 7 pruned.

Trial 7, Epoch 1/30, Train Loss: 0.2202, Val Loss: 0.2603, KL Weight: 0.0505, Train Recon. Loss: 0.1345, Val Recon. Loss: 0.19766172893569434
Trial 8, Epoch 1/30, Train Loss: 0.3938, Val Loss: 0.3735, KL Weight: 0.0505, Train Recon. Loss: 0.1030, Val Recon. Loss: 0.086849181519894
Trial 8, Epoch 2/30, Train Loss: 0.3465, Val Loss: 0.3376, KL Weight: 0.0505, Train Recon. Loss: 0.0640, Val Recon. Loss: 0.05894504042619185
Trial 8, Epoch 3/30, Train Loss: 0.3052, Val Loss: 0.3128, KL Weight: 0.0502, Train Recon. Loss: 0.0318, Val Recon. Loss: 0.04299460240994935
Trial 8, Epoch 4/30, Train Loss: 0.2825, Val Loss: 0.2997, KL Weight: 0.0481, Train Recon. Loss: 0.0269, Val Recon. Loss: 0.047439522546221004
Trial 8, Epoch 5/30, Train Loss: 0.2185, Val Loss: 0.2216, KL Weight: 0.0371, Train Recon. Loss: 0.0261, Val Recon. Loss: 0.031173891291391472
Trial 8, Epoch 6/30, Train Loss: 0.0953, Val Loss: 0.1034, KL Weight: 0.0139, Train Recon. Loss: 0.0238, Val Recon. Loss: 0.03200012848883107
Trial 8, Epoch 7/30, Train Loss: 0.0408, Val Loss: 0.0499, KL Weight: 0.0029, Train Recon. Loss: 0.0261, Val Recon. Loss: 0.03511213410649919
Trial 8, Epoch 8/30, Train Loss: 0.0280, Val Loss: 0.0346, KL Weight: 0.0008, Train Recon. Loss: 0.0237, Val Recon. Loss: 0.03021420435539472
Trial 8, Epoch 9/30, Train Loss: 0.0255, Val Loss: 0.0342, KL Weight: 0.0005, Train Recon. Loss: 0.0227, Val Recon. Loss: 0.03138263473027126
Trial 8, Epoch 10/30, Train Loss: 0.0252, Val Loss: 0.0375, KL Weight: 0.0005, Train Recon. Loss: 0.0225, Val Recon. Loss: 0.03485128099403649
Trial 8, Epoch 11/30, Train Loss: 0.0240, Val Loss: 0.0289, KL Weight: 0.0005, Train Recon. Loss: 0.0213, Val Recon. Loss: 0.026270670525438793
Trial 8, Epoch 12/30, Train Loss: 0.0228, Val Loss: 0.0310, KL Weight: 0.0005, Train Recon. Loss: 0.0201, Val Recon. Loss: 0.028336344141717273
Trial 8, Epoch 13/30, Train Loss: 0.0233, Val Loss: 0.0317, KL Weight: 0.0005, Train Recon. Loss: 0.0206, Val Recon. Loss: 0.028986166167707817
Trial 8, Epoch 14/30, Train Loss: 0.0216, Val Loss: 0.0248, KL Weight: 0.0005, Train Recon. Loss: 0.0189, Val Recon. Loss: 0.02199774672201759
Trial 8, Epoch 15/30, Train Loss: 0.0200, Val Loss: 0.0291, KL Weight: 0.0005, Train Recon. Loss: 0.0172, Val Recon. Loss: 0.026285499134366667
Trial 8, Epoch 16/30, Train Loss: 0.0208, Val Loss: 0.0208, KL Weight: 0.0005, Train Recon. Loss: 0.0180, Val Recon. Loss: 0.01800741358274208
Trial 8, Epoch 17/30, Train Loss: 0.0188, Val Loss: 0.0263, KL Weight: 0.0005, Train Recon. Loss: 0.0160, Val Recon. Loss: 0.023496394472856733
Trial 8, Epoch 18/30, Train Loss: 0.0199, Val Loss: 0.0183, KL Weight: 0.0005, Train Recon. Loss: 0.0170, Val Recon. Loss: 0.015454243754096856
Trial 8, Epoch 19/30, Train Loss: 0.0197, Val Loss: 0.0316, KL Weight: 0.0005, Train Recon. Loss: 0.0168, Val Recon. Loss: 0.02872534327043987
Trial 8, Epoch 20/30, Train Loss: 0.0186, Val Loss: 0.0248, KL Weight: 0.0005, Train Recon. Loss: 0.0157, Val Recon. Loss: 0.021901440090365574
Trial 8, Epoch 21/30, Train Loss: 0.0186, Val Loss: 0.0178, KL Weight: 0.0005, Train Recon. Loss: 0.0157, Val Recon. Loss: 0.01489387577320603
Trial 8, Epoch 22/30, Train Loss: 0.0185, Val Loss: 0.0265, KL Weight: 0.0005, Train Recon. Loss: 0.0155, Val Recon. Loss: 0.023537811990645533
Trial 8, Epoch 23/30, Train Loss: 0.0175, Val Loss: 0.0223, KL Weight: 0.0005, Train Recon. Loss: 0.0146, Val Recon. Loss: 0.019309471601860837
Trial 8, Epoch 24/30, Train Loss: 0.0186, Val Loss: 0.0289, KL Weight: 0.0005, Train Recon. Loss: 0.0157, Val Recon. Loss: 0.025954215160875885
Trial 8, Epoch 25/30, Train Loss: 0.0165, Val Loss: 0.0260, KL Weight: 0.0005, Train Recon. Loss: 0.0135, Val Recon. Loss: 0.023017086054222216
Trial 8, Epoch 26/30, Train Loss: 0.0178, Val Loss: 0.0287, KL Weight: 0.0005, Train Recon. Loss: 0.0148, Val Recon. Loss: 0.025623465428134432
Trial 8, Epoch 27/30, Train Loss: 0.0154, Val Loss: 0.0203, KL Weight: 0.0005, Train Recon. Loss: 0.0123, Val Recon. Loss: 0.01722451277579217
Trial 8, Epoch 28/30, Train Loss: 0.0163, Val Loss: 0.0134, KL Weight: 0.0005, Train Recon. Loss: 0.0133, Val Recon. Loss: 0.010330546553968242
Trial 8, Epoch 29/30, Train Loss: 0.0150, Val Loss: 0.0181, KL Weight: 0.0005, Train Recon. Loss: 0.0119, Val Recon. Loss: 0.014988706042702022

[I 2025-02-16 21:28:06,432] Trial 8 finished with value: 0.025507869668075587 and parameters: {'lr': 0.00014667998629117832, 'batch_size': 512, 'hidden_size1': 96, 'hidden_size2': 96, 'hidden_size3': 64}. Best is trial 5 with value: 0.017414332954101153.

Trial 8, Epoch 30/30, Train Loss: 0.0154, Val Loss: 0.0286, KL Weight: 0.0005, Train Recon. Loss: 0.0123, Val Recon. Loss: 0.025507869668075587
Trial 9, Epoch 1/30, Train Loss: 0.3736, Val Loss: 0.3409, KL Weight: 0.0505, Train Recon. Loss: 0.0973, Val Recon. Loss: 0.07421300560568593
Trial 9, Epoch 2/30, Train Loss: 0.3220, Val Loss: 0.3081, KL Weight: 0.0505, Train Recon. Loss: 0.0646, Val Recon. Loss: 0.05969173122421467
Trial 9, Epoch 3/30, Train Loss: 0.2808, Val Loss: 0.2837, KL Weight: 0.0502, Train Recon. Loss: 0.0420, Val Recon. Loss: 0.05271718854336698
Trial 9, Epoch 4/30, Train Loss: 0.2520, Val Loss: 0.2630, KL Weight: 0.0481, Train Recon. Loss: 0.0371, Val Recon. Loss: 0.05458207046122927
Trial 9, Epoch 5/30, Train Loss: 0.1968, Val Loss: 0.1953, KL Weight: 0.0371, Train Recon. Loss: 0.0394, Val Recon. Loss: 0.040940277884133104
Trial 9, Epoch 6/30, Train Loss: 0.0959, Val Loss: 0.1028, KL Weight: 0.0139, Train Recon. Loss: 0.0375, Val Recon. Loss: 0.043998927556510484
Trial 9, Epoch 7/30, Train Loss: 0.0477, Val Loss: 0.0533, KL Weight: 0.0029, Train Recon. Loss: 0.0353, Val Recon. Loss: 0.040751726270646306
Trial 9, Epoch 8/30, Train Loss: 0.0348, Val Loss: 0.0321, KL Weight: 0.0008, Train Recon. Loss: 0.0311, Val Recon. Loss: 0.028325069761358873
Trial 9, Epoch 9/30, Train Loss: 0.0305, Val Loss: 0.0378, KL Weight: 0.0005, Train Recon. Loss: 0.0280, Val Recon. Loss: 0.03521519901591556
Trial 9, Epoch 10/30, Train Loss: 0.0285, Val Loss: 0.0310, KL Weight: 0.0005, Train Recon. Loss: 0.0261, Val Recon. Loss: 0.02853419153593985
Trial 9, Epoch 11/30, Train Loss: 0.0250, Val Loss: 0.0368, KL Weight: 0.0005, Train Recon. Loss: 0.0226, Val Recon. Loss: 0.034300326562006926
Trial 9, Epoch 12/30, Train Loss: 0.0238, Val Loss: 0.0291, KL Weight: 0.0005, Train Recon. Loss: 0.0213, Val Recon. Loss: 0.026586952384323216
Trial 9, Epoch 13/30, Train Loss: 0.0215, Val Loss: 0.0254, KL Weight: 0.0005, Train Recon. Loss: 0.0190, Val Recon. Loss: 0.022807635016620326
Trial 9, Epoch 14/30, Train Loss: 0.0207, Val Loss: 0.0189, KL Weight: 0.0005, Train Recon. Loss: 0.0180, Val Recon. Loss: 0.0162919588642601
Trial 9, Epoch 15/30, Train Loss: 0.0189, Val Loss: 0.0229, KL Weight: 0.0005, Train Recon. Loss: 0.0162, Val Recon. Loss: 0.02016839632953524
Trial 9, Epoch 16/30, Train Loss: 0.0176, Val Loss: 0.0270, KL Weight: 0.0005, Train Recon. Loss: 0.0149, Val Recon. Loss: 0.0242044500772022
Trial 9, Epoch 17/30, Train Loss: 0.0172, Val Loss: 0.0194, KL Weight: 0.0005, Train Recon. Loss: 0.0144, Val Recon. Loss: 0.016615201739499808
Trial 9, Epoch 18/30, Train Loss: 0.0166, Val Loss: 0.0209, KL Weight: 0.0005, Train Recon. Loss: 0.0137, Val Recon. Loss: 0.018060192388843016
Trial 9, Epoch 19/30, Train Loss: 0.0155, Val Loss: 0.0190, KL Weight: 0.0005, Train Recon. Loss: 0.0126, Val Recon. Loss: 0.016065851865857978
Trial 9, Epoch 20/30, Train Loss: 0.0150, Val Loss: 0.0187, KL Weight: 0.0005, Train Recon. Loss: 0.0121, Val Recon. Loss: 0.015694509848122505
Trial 9, Epoch 21/30, Train Loss: 0.0145, Val Loss: 0.0199, KL Weight: 0.0005, Train Recon. Loss: 0.0115, Val Recon. Loss: 0.01691742240095903
Trial 9, Epoch 22/30, Train Loss: 0.0141, Val Loss: 0.0165, KL Weight: 0.0005, Train Recon. Loss: 0.0110, Val Recon. Loss: 0.01340044748302395
Trial 9, Epoch 23/30, Train Loss: 0.0139, Val Loss: 0.0134, KL Weight: 0.0005, Train Recon. Loss: 0.0108, Val Recon. Loss: 0.01025432180924012
Trial 9, Epoch 24/30, Train Loss: 0.0133, Val Loss: 0.0160, KL Weight: 0.0005, Train Recon. Loss: 0.0102, Val Recon. Loss: 0.012863043958585556
Trial 9, Epoch 25/30, Train Loss: 0.0125, Val Loss: 0.0150, KL Weight: 0.0005, Train Recon. Loss: 0.0093, Val Recon. Loss: 0.011768165535662898
Trial 9, Epoch 26/30, Train Loss: 0.0126, Val Loss: 0.0159, KL Weight: 0.0005, Train Recon. Loss: 0.0094, Val Recon. Loss: 0.012609433691118865
Trial 9, Epoch 27/30, Train Loss: 0.0129, Val Loss: 0.0164, KL Weight: 0.0005, Train Recon. Loss: 0.0097, Val Recon. Loss: 0.013161007418118669
Trial 9, Epoch 28/30, Train Loss: 0.0122, Val Loss: 0.0154, KL Weight: 0.0005, Train Recon. Loss: 0.0089, Val Recon. Loss: 0.012118709765031542
Trial 9, Epoch 29/30, Train Loss: 0.0116, Val Loss: 0.0107, KL Weight: 0.0005, Train Recon. Loss: 0.0083, Val Recon. Loss: 0.007319782900403401

[I 2025-02-16 21:32:00,735] Trial 9 finished with value: 0.011827676282246785 and parameters: {'lr': 0.0001804978313277879, 'batch_size': 256, 'hidden_size1': 48, 'hidden_size2': 64, 'hidden_size3': 32}. Best is trial 9 with value: 0.011827676282246785.

Trial 9, Epoch 30/30, Train Loss: 0.0119, Val Loss: 0.0152, KL Weight: 0.0005, Train Recon. Loss: 0.0085, Val Recon. Loss: 0.011827676282246785
Trial 10, Epoch 1/30, Train Loss: 0.3628, Val Loss: 0.3342, KL Weight: 0.0505, Train Recon. Loss: 0.0972, Val Recon. Loss: 0.0883298848020403
Trial 10, Epoch 2/30, Train Loss: 0.3025, Val Loss: 0.2945, KL Weight: 0.0505, Train Recon. Loss: 0.0747, Val Recon. Loss: 0.0829718960389579
Trial 10, Epoch 3/30, Train Loss: 0.2512, Val Loss: 0.2419, KL Weight: 0.0502, Train Recon. Loss: 0.0538, Val Recon. Loss: 0.0560386941701706
Trial 10, Epoch 4/30, Train Loss: 0.2261, Val Loss: 0.2221, KL Weight: 0.0481, Train Recon. Loss: 0.0561, Val Recon. Loss: 0.059649664061354066
Trial 10, Epoch 5/30, Train Loss: 0.1792, Val Loss: 0.1890, KL Weight: 0.0371, Train Recon. Loss: 0.0568, Val Recon. Loss: 0.06920544169808185
Trial 10, Epoch 6/30, Train Loss: 0.1000, Val Loss: 0.1037, KL Weight: 0.0139, Train Recon. Loss: 0.0534, Val Recon. Loss: 0.05591255806848631
Trial 10, Epoch 7/30, Train Loss: 0.0548, Val Loss: 0.0518, KL Weight: 0.0029, Train Recon. Loss: 0.0445, Val Recon. Loss: 0.041104612441180285
Trial 10, Epoch 8/30, Train Loss: 0.0377, Val Loss: 0.0390, KL Weight: 0.0008, Train Recon. Loss: 0.0345, Val Recon. Loss: 0.03562215710202358
Trial 10, Epoch 9/30, Train Loss: 0.0325, Val Loss: 0.0380, KL Weight: 0.0005, Train Recon. Loss: 0.0302, Val Recon. Loss: 0.03563440504529394
Trial 10, Epoch 10/30, Train Loss: 0.0279, Val Loss: 0.0278, KL Weight: 0.0005, Train Recon. Loss: 0.0256, Val Recon. Loss: 0.025456518800649093
Trial 10, Epoch 11/30, Train Loss: 0.0245, Val Loss: 0.0267, KL Weight: 0.0005, Train Recon. Loss: 0.0222, Val Recon. Loss: 0.024239708262117566
Trial 10, Epoch 12/30, Train Loss: 0.0229, Val Loss: 0.0248, KL Weight: 0.0005, Train Recon. Loss: 0.0205, Val Recon. Loss: 0.02228243584640471
Trial 10, Epoch 13/30, Train Loss: 0.0213, Val Loss: 0.0294, KL Weight: 0.0005, Train Recon. Loss: 0.0187, Val Recon. Loss: 0.02671209413250138
Trial 10, Epoch 14/30, Train Loss: 0.0207, Val Loss: 0.0348, KL Weight: 0.0005, Train Recon. Loss: 0.0180, Val Recon. Loss: 0.03205261088599612
Trial 10, Epoch 15/30, Train Loss: 0.0187, Val Loss: 0.0217, KL Weight: 0.0005, Train Recon. Loss: 0.0159, Val Recon. Loss: 0.018825046584986963
Trial 10, Epoch 16/30, Train Loss: 0.0181, Val Loss: 0.0199, KL Weight: 0.0005, Train Recon. Loss: 0.0152, Val Recon. Loss: 0.016934269087921297
Trial 10, Epoch 17/30, Train Loss: 0.0167, Val Loss: 0.0247, KL Weight: 0.0005, Train Recon. Loss: 0.0137, Val Recon. Loss: 0.0216445034166756
Trial 10, Epoch 18/30, Train Loss: 0.0155, Val Loss: 0.0219, KL Weight: 0.0005, Train Recon. Loss: 0.0124, Val Recon. Loss: 0.01877108462841103
Trial 10, Epoch 19/30, Train Loss: 0.0149, Val Loss: 0.0181, KL Weight: 0.0005, Train Recon. Loss: 0.0118, Val Recon. Loss: 0.014910222404011476
Trial 10, Epoch 20/30, Train Loss: 0.0149, Val Loss: 0.0159, KL Weight: 0.0005, Train Recon. Loss: 0.0117, Val Recon. Loss: 0.01264057371741742
Trial 10, Epoch 21/30, Train Loss: 0.0133, Val Loss: 0.0161, KL Weight: 0.0005, Train Recon. Loss: 0.0100, Val Recon. Loss: 0.012739350532769764
Trial 10, Epoch 22/30, Train Loss: 0.0128, Val Loss: 0.0156, KL Weight: 0.0005, Train Recon. Loss: 0.0095, Val Recon. Loss: 0.012246645748645025
Trial 10, Epoch 23/30, Train Loss: 0.0137, Val Loss: 0.0142, KL Weight: 0.0005, Train Recon. Loss: 0.0102, Val Recon. Loss: 0.010762380122266626
Trial 10, Epoch 24/30, Train Loss: 0.0128, Val Loss: 0.0149, KL Weight: 0.0005, Train Recon. Loss: 0.0094, Val Recon. Loss: 0.011370696547866582
Trial 10, Epoch 25/30, Train Loss: 0.0122, Val Loss: 0.0140, KL Weight: 0.0005, Train Recon. Loss: 0.0087, Val Recon. Loss: 0.010444528874205916
Trial 10, Epoch 26/30, Train Loss: 0.0126, Val Loss: 0.0107, KL Weight: 0.0005, Train Recon. Loss: 0.0090, Val Recon. Loss: 0.007143233930105623
Trial 10, Epoch 27/30, Train Loss: 0.0128, Val Loss: 0.0134, KL Weight: 0.0005, Train Recon. Loss: 0.0092, Val Recon. Loss: 0.009775138495637006
Trial 10, Epoch 28/30, Train Loss: 0.0121, Val Loss: 0.0178, KL Weight: 0.0005, Train Recon. Loss: 0.0085, Val Recon. Loss: 0.014175723011332348
Trial 10, Epoch 29/30, Train Loss: 0.0132, Val Loss: 0.0203, KL Weight: 0.0005, Train Recon. Loss: 0.0096, Val Recon. Loss: 0.016696901334610704

[I 2025-02-16 21:35:55,971] Trial 10 finished with value: 0.01740690614849581 and parameters: {'lr': 0.00036775752536834656, 'batch_size': 256, 'hidden_size1': 16, 'hidden_size2': 48, 'hidden_size3': 8}. Best is trial 9 with value: 0.011827676282246785.

Trial 10, Epoch 30/30, Train Loss: 0.0117, Val Loss: 0.0211, KL Weight: 0.0005, Train Recon. Loss: 0.0080, Val Recon. Loss: 0.01740690614849581

[I 2025-02-16 21:36:03,818] Trial 11 pruned.

Trial 11, Epoch 1/30, Train Loss: 0.2274, Val Loss: 0.3971, KL Weight: 0.0505, Train Recon. Loss: 0.1604, Val Recon. Loss: 0.32518176516532

[I 2025-02-16 21:36:11,660] Trial 12 pruned.

Trial 12, Epoch 1/30, Train Loss: 0.3892, Val Loss: 0.3699, KL Weight: 0.0505, Train Recon. Loss: 0.1170, Val Recon. Loss: 0.11172315239647221
Trial 13, Epoch 1/30, Train Loss: 0.3903, Val Loss: 0.3707, KL Weight: 0.0505, Train Recon. Loss: 0.1122, Val Recon. Loss: 0.09650051262320712
Trial 13, Epoch 2/30, Train Loss: 0.3520, Val Loss: 0.3371, KL Weight: 0.0505, Train Recon. Loss: 0.0818, Val Recon. Loss: 0.07064212883001586
Trial 13, Epoch 3/30, Train Loss: 0.3209, Val Loss: 0.3129, KL Weight: 0.0502, Train Recon. Loss: 0.0596, Val Recon. Loss: 0.05512351887029267
Trial 13, Epoch 4/30, Train Loss: 0.2849, Val Loss: 0.2867, KL Weight: 0.0481, Train Recon. Loss: 0.0408, Val Recon. Loss: 0.04559835162244849
Trial 13, Epoch 5/30, Train Loss: 0.2142, Val Loss: 0.2183, KL Weight: 0.0371, Train Recon. Loss: 0.0303, Val Recon. Loss: 0.036183264509151526
Trial 13, Epoch 6/30, Train Loss: 0.0993, Val Loss: 0.1096, KL Weight: 0.0139, Train Recon. Loss: 0.0308, Val Recon. Loss: 0.04106221431025997
Trial 13, Epoch 7/30, Train Loss: 0.0429, Val Loss: 0.0479, KL Weight: 0.0029, Train Recon. Loss: 0.0287, Val Recon. Loss: 0.03359687460229305
Trial 13, Epoch 8/30, Train Loss: 0.0316, Val Loss: 0.0323, KL Weight: 0.0008, Train Recon. Loss: 0.0274, Val Recon. Loss: 0.028118908206785195
Trial 13, Epoch 9/30, Train Loss: 0.0283, Val Loss: 0.0327, KL Weight: 0.0005, Train Recon. Loss: 0.0256, Val Recon. Loss: 0.029882269830896372
Trial 13, Epoch 10/30, Train Loss: 0.0271, Val Loss: 0.0351, KL Weight: 0.0005, Train Recon. Loss: 0.0245, Val Recon. Loss: 0.032454209115804364
Trial 13, Epoch 11/30, Train Loss: 0.0261, Val Loss: 0.0287, KL Weight: 0.0005, Train Recon. Loss: 0.0235, Val Recon. Loss: 0.026128443472150407
Trial 13, Epoch 12/30, Train Loss: 0.0252, Val Loss: 0.0262, KL Weight: 0.0005, Train Recon. Loss: 0.0226, Val Recon. Loss: 0.02350999077946592
Trial 13, Epoch 13/30, Train Loss: 0.0246, Val Loss: 0.0359, KL Weight: 0.0005, Train Recon. Loss: 0.0220, Val Recon. Loss: 0.03325675726567108
Trial 13, Epoch 14/30, Train Loss: 0.0234, Val Loss: 0.0290, KL Weight: 0.0005, Train Recon. Loss: 0.0208, Val Recon. Loss: 0.026305065446102612
Trial 13, Epoch 15/30, Train Loss: 0.0222, Val Loss: 0.0325, KL Weight: 0.0005, Train Recon. Loss: 0.0195, Val Recon. Loss: 0.029726234402794642
Trial 13, Epoch 16/30, Train Loss: 0.0221, Val Loss: 0.0214, KL Weight: 0.0005, Train Recon. Loss: 0.0193, Val Recon. Loss: 0.01868008414740303
Trial 13, Epoch 17/30, Train Loss: 0.0210, Val Loss: 0.0257, KL Weight: 0.0005, Train Recon. Loss: 0.0182, Val Recon. Loss: 0.0228766334855831
Trial 13, Epoch 18/30, Train Loss: 0.0197, Val Loss: 0.0220, KL Weight: 0.0005, Train Recon. Loss: 0.0169, Val Recon. Loss: 0.019208885895270377
Trial 13, Epoch 19/30, Train Loss: 0.0193, Val Loss: 0.0253, KL Weight: 0.0005, Train Recon. Loss: 0.0165, Val Recon. Loss: 0.022498461751344342
Trial 13, Epoch 20/30, Train Loss: 0.0189, Val Loss: 0.0251, KL Weight: 0.0005, Train Recon. Loss: 0.0160, Val Recon. Loss: 0.022235777369994474
Trial 13, Epoch 21/30, Train Loss: 0.0185, Val Loss: 0.0258, KL Weight: 0.0005, Train Recon. Loss: 0.0156, Val Recon. Loss: 0.02285688288187734
Trial 13, Epoch 22/30, Train Loss: 0.0189, Val Loss: 0.0270, KL Weight: 0.0005, Train Recon. Loss: 0.0159, Val Recon. Loss: 0.02410772464665255
Trial 13, Epoch 23/30, Train Loss: 0.0173, Val Loss: 0.0241, KL Weight: 0.0005, Train Recon. Loss: 0.0144, Val Recon. Loss: 0.02109343705101891
Trial 13, Epoch 24/30, Train Loss: 0.0172, Val Loss: 0.0218, KL Weight: 0.0005, Train Recon. Loss: 0.0142, Val Recon. Loss: 0.018846730054951365
Trial 13, Epoch 25/30, Train Loss: 0.0168, Val Loss: 0.0202, KL Weight: 0.0005, Train Recon. Loss: 0.0138, Val Recon. Loss: 0.017167090946682412
Trial 13, Epoch 26/30, Train Loss: 0.0163, Val Loss: 0.0221, KL Weight: 0.0005, Train Recon. Loss: 0.0133, Val Recon. Loss: 0.01908378405513984
Trial 13, Epoch 27/30, Train Loss: 0.0156, Val Loss: 0.0271, KL Weight: 0.0005, Train Recon. Loss: 0.0125, Val Recon. Loss: 0.024052983515062614
Trial 13, Epoch 28/30, Train Loss: 0.0157, Val Loss: 0.0206, KL Weight: 0.0005, Train Recon. Loss: 0.0126, Val Recon. Loss: 0.01751269679779145
Trial 13, Epoch 29/30, Train Loss: 0.0149, Val Loss: 0.0252, KL Weight: 0.0005, Train Recon. Loss: 0.0118, Val Recon. Loss: 0.0220720175278191

[I 2025-02-16 21:40:01,563] Trial 13 finished with value: 0.013953932615402294 and parameters: {'lr': 7.733369440646535e-05, 'batch_size': 256, 'hidden_size1': 32, 'hidden_size2': 64, 'hidden_size3': 40}. Best is trial 9 with value: 0.011827676282246785.

Trial 13, Epoch 30/30, Train Loss: 0.0148, Val Loss: 0.0171, KL Weight: 0.0005, Train Recon. Loss: 0.0117, Val Recon. Loss: 0.013953932615402294
Trial 14, Epoch 1/30, Train Loss: 0.3906, Val Loss: 0.3795, KL Weight: 0.0505, Train Recon. Loss: 0.1072, Val Recon. Loss: 0.10019334319320725
Trial 14, Epoch 2/30, Train Loss: 0.3556, Val Loss: 0.3336, KL Weight: 0.0505, Train Recon. Loss: 0.0805, Val Recon. Loss: 0.06245361845765291
Trial 14, Epoch 3/30, Train Loss: 0.3101, Val Loss: 0.3054, KL Weight: 0.0502, Train Recon. Loss: 0.0442, Val Recon. Loss: 0.04306099002995297
Trial 14, Epoch 4/30, Train Loss: 0.2765, Val Loss: 0.2837, KL Weight: 0.0481, Train Recon. Loss: 0.0281, Val Recon. Loss: 0.0386683552911071
Trial 14, Epoch 5/30, Train Loss: 0.2155, Val Loss: 0.2166, KL Weight: 0.0371, Train Recon. Loss: 0.0287, Val Recon. Loss: 0.03163974179888032
Trial 14, Epoch 6/30, Train Loss: 0.0972, Val Loss: 0.1075, KL Weight: 0.0139, Train Recon. Loss: 0.0276, Val Recon. Loss: 0.037985784732351514
Trial 14, Epoch 7/30, Train Loss: 0.0415, Val Loss: 0.0407, KL Weight: 0.0029, Train Recon. Loss: 0.0271, Val Recon. Loss: 0.02621018942406128
Trial 14, Epoch 8/30, Train Loss: 0.0294, Val Loss: 0.0306, KL Weight: 0.0008, Train Recon. Loss: 0.0251, Val Recon. Loss: 0.026304395377103773
Trial 14, Epoch 9/30, Train Loss: 0.0262, Val Loss: 0.0302, KL Weight: 0.0005, Train Recon. Loss: 0.0234, Val Recon. Loss: 0.0274024312440446
Trial 14, Epoch 10/30, Train Loss: 0.0256, Val Loss: 0.0282, KL Weight: 0.0005, Train Recon. Loss: 0.0230, Val Recon. Loss: 0.025516525564428166
Trial 14, Epoch 11/30, Train Loss: 0.0245, Val Loss: 0.0325, KL Weight: 0.0005, Train Recon. Loss: 0.0219, Val Recon. Loss: 0.029880177234106915
Trial 14, Epoch 12/30, Train Loss: 0.0235, Val Loss: 0.0260, KL Weight: 0.0005, Train Recon. Loss: 0.0208, Val Recon. Loss: 0.0233248487085146
Trial 14, Epoch 13/30, Train Loss: 0.0237, Val Loss: 0.0248, KL Weight: 0.0005, Train Recon. Loss: 0.0210, Val Recon. Loss: 0.022073691569205682
Trial 14, Epoch 14/30, Train Loss: 0.0214, Val Loss: 0.0269, KL Weight: 0.0005, Train Recon. Loss: 0.0187, Val Recon. Loss: 0.02413148225453171
Trial 14, Epoch 15/30, Train Loss: 0.0206, Val Loss: 0.0263, KL Weight: 0.0005, Train Recon. Loss: 0.0179, Val Recon. Loss: 0.0235510683471435
Trial 14, Epoch 16/30, Train Loss: 0.0197, Val Loss: 0.0254, KL Weight: 0.0005, Train Recon. Loss: 0.0169, Val Recon. Loss: 0.0226449921006806
Trial 14, Epoch 17/30, Train Loss: 0.0195, Val Loss: 0.0214, KL Weight: 0.0005, Train Recon. Loss: 0.0167, Val Recon. Loss: 0.018530773727881505
Trial 14, Epoch 18/30, Train Loss: 0.0185, Val Loss: 0.0276, KL Weight: 0.0005, Train Recon. Loss: 0.0157, Val Recon. Loss: 0.024740166613601036
Trial 14, Epoch 19/30, Train Loss: 0.0182, Val Loss: 0.0223, KL Weight: 0.0005, Train Recon. Loss: 0.0153, Val Recon. Loss: 0.019407803770784934
Trial 14, Epoch 20/30, Train Loss: 0.0177, Val Loss: 0.0196, KL Weight: 0.0005, Train Recon. Loss: 0.0148, Val Recon. Loss: 0.01671351871988911
Trial 14, Epoch 21/30, Train Loss: 0.0168, Val Loss: 0.0208, KL Weight: 0.0005, Train Recon. Loss: 0.0139, Val Recon. Loss: 0.017913480369020532
Trial 14, Epoch 22/30, Train Loss: 0.0161, Val Loss: 0.0171, KL Weight: 0.0005, Train Recon. Loss: 0.0132, Val Recon. Loss: 0.014135162366700317
Trial 14, Epoch 23/30, Train Loss: 0.0162, Val Loss: 0.0175, KL Weight: 0.0005, Train Recon. Loss: 0.0132, Val Recon. Loss: 0.01451643115258338
Trial 14, Epoch 24/30, Train Loss: 0.0160, Val Loss: 0.0209, KL Weight: 0.0005, Train Recon. Loss: 0.0130, Val Recon. Loss: 0.017859146113269365
Trial 14, Epoch 25/30, Train Loss: 0.0157, Val Loss: 0.0228, KL Weight: 0.0005, Train Recon. Loss: 0.0127, Val Recon. Loss: 0.019774498959392296
Trial 14, Epoch 26/30, Train Loss: 0.0146, Val Loss: 0.0149, KL Weight: 0.0005, Train Recon. Loss: 0.0116, Val Recon. Loss: 0.011874965565625745
Trial 14, Epoch 27/30, Train Loss: 0.0145, Val Loss: 0.0187, KL Weight: 0.0005, Train Recon. Loss: 0.0114, Val Recon. Loss: 0.015580336292076478
Trial 14, Epoch 28/30, Train Loss: 0.0145, Val Loss: 0.0159, KL Weight: 0.0005, Train Recon. Loss: 0.0114, Val Recon. Loss: 0.012795544215705583
Trial 14, Epoch 29/30, Train Loss: 0.0140, Val Loss: 0.0161, KL Weight: 0.0005, Train Recon. Loss: 0.0109, Val Recon. Loss: 0.012940674789137858

[I 2025-02-16 21:43:52,883] Trial 14 finished with value: 0.01211333294391205 and parameters: {'lr': 7.609770168177761e-05, 'batch_size': 256, 'hidden_size1': 48, 'hidden_size2': 64, 'hidden_size3': 40}. Best is trial 9 with value: 0.011827676282246785.

Trial 14, Epoch 30/30, Train Loss: 0.0140, Val Loss: 0.0153, KL Weight: 0.0005, Train Recon. Loss: 0.0108, Val Recon. Loss: 0.01211333294391205
Trial 15, Epoch 1/30, Train Loss: 0.3275, Val Loss: 0.2633, KL Weight: 0.0505, Train Recon. Loss: 0.0978, Val Recon. Loss: 0.08205197695362612
Trial 15, Epoch 2/30, Train Loss: 0.2382, Val Loss: 0.2328, KL Weight: 0.0505, Train Recon. Loss: 0.0844, Val Recon. Loss: 0.09974863563727279

[I 2025-02-16 21:44:16,442] Trial 15 pruned.

Trial 15, Epoch 3/30, Train Loss: 0.2036, Val Loss: 0.2137, KL Weight: 0.0502, Train Recon. Loss: 0.0801, Val Recon. Loss: 0.09786665014418444

[I 2025-02-16 21:44:24,293] Trial 16 pruned.

Trial 16, Epoch 1/30, Train Loss: 0.4065, Val Loss: 0.3963, KL Weight: 0.0505, Train Recon. Loss: 0.1111, Val Recon. Loss: 0.10404447298847083

[I 2025-02-16 21:44:32,156] Trial 17 pruned.

Trial 17, Epoch 1/30, Train Loss: 0.3432, Val Loss: 0.3091, KL Weight: 0.0505, Train Recon. Loss: 0.1024, Val Recon. Loss: 0.11306545051528995

[I 2025-02-16 21:44:40,038] Trial 18 pruned.

Trial 18, Epoch 1/30, Train Loss: 0.4061, Val Loss: 0.3870, KL Weight: 0.0505, Train Recon. Loss: 0.1210, Val Recon. Loss: 0.10355339342836795
Trial 19, Epoch 1/30, Train Loss: 0.3712, Val Loss: 0.3504, KL Weight: 0.0505, Train Recon. Loss: 0.0966, Val Recon. Loss: 0.08202358282038144
Trial 19, Epoch 2/30, Train Loss: 0.3128, Val Loss: 0.3054, KL Weight: 0.0505, Train Recon. Loss: 0.0506, Val Recon. Loss: 0.048698676871380915
Trial 19, Epoch 3/30, Train Loss: 0.2807, Val Loss: 0.2851, KL Weight: 0.0502, Train Recon. Loss: 0.0307, Val Recon. Loss: 0.040251131201709124
Trial 19, Epoch 4/30, Train Loss: 0.2613, Val Loss: 0.2710, KL Weight: 0.0481, Train Recon. Loss: 0.0311, Val Recon. Loss: 0.045496648461803006
Trial 19, Epoch 5/30, Train Loss: 0.2045, Val Loss: 0.2019, KL Weight: 0.0371, Train Recon. Loss: 0.0333, Val Recon. Loss: 0.03300328256537844
Trial 19, Epoch 6/30, Train Loss: 0.0957, Val Loss: 0.0995, KL Weight: 0.0139, Train Recon. Loss: 0.0319, Val Recon. Loss: 0.03560302164510621
Trial 19, Epoch 7/30, Train Loss: 0.0442, Val Loss: 0.0500, KL Weight: 0.0029, Train Recon. Loss: 0.0309, Val Recon. Loss: 0.036580508298422666
Trial 19, Epoch 8/30, Train Loss: 0.0324, Val Loss: 0.0364, KL Weight: 0.0008, Train Recon. Loss: 0.0284, Val Recon. Loss: 0.03244818748251528
Trial 19, Epoch 9/30, Train Loss: 0.0291, Val Loss: 0.0408, KL Weight: 0.0005, Train Recon. Loss: 0.0264, Val Recon. Loss: 0.03816584311548228
Trial 19, Epoch 10/30, Train Loss: 0.0274, Val Loss: 0.0344, KL Weight: 0.0005, Train Recon. Loss: 0.0249, Val Recon. Loss: 0.031852469256207265
Trial 19, Epoch 11/30, Train Loss: 0.0247, Val Loss: 0.0306, KL Weight: 0.0005, Train Recon. Loss: 0.0222, Val Recon. Loss: 0.028033756283356956
Trial 19, Epoch 12/30, Train Loss: 0.0237, Val Loss: 0.0257, KL Weight: 0.0005, Train Recon. Loss: 0.0211, Val Recon. Loss: 0.023093929898371935
Trial 19, Epoch 13/30, Train Loss: 0.0224, Val Loss: 0.0203, KL Weight: 0.0005, Train Recon. Loss: 0.0197, Val Recon. Loss: 0.017680910754339644
Trial 19, Epoch 14/30, Train Loss: 0.0211, Val Loss: 0.0270, KL Weight: 0.0005, Train Recon. Loss: 0.0184, Val Recon. Loss: 0.024365501932596744
Trial 19, Epoch 15/30, Train Loss: 0.0204, Val Loss: 0.0228, KL Weight: 0.0005, Train Recon. Loss: 0.0177, Val Recon. Loss: 0.020079310944205835
Trial 19, Epoch 16/30, Train Loss: 0.0195, Val Loss: 0.0221, KL Weight: 0.0005, Train Recon. Loss: 0.0168, Val Recon. Loss: 0.019302705116745058
Trial 19, Epoch 17/30, Train Loss: 0.0185, Val Loss: 0.0256, KL Weight: 0.0005, Train Recon. Loss: 0.0157, Val Recon. Loss: 0.022771412312032138
Trial 19, Epoch 18/30, Train Loss: 0.0178, Val Loss: 0.0215, KL Weight: 0.0005, Train Recon. Loss: 0.0150, Val Recon. Loss: 0.018685466107121088
Trial 19, Epoch 19/30, Train Loss: 0.0170, Val Loss: 0.0220, KL Weight: 0.0005, Train Recon. Loss: 0.0141, Val Recon. Loss: 0.019141700945066332
Trial 19, Epoch 20/30, Train Loss: 0.0162, Val Loss: 0.0164, KL Weight: 0.0005, Train Recon. Loss: 0.0133, Val Recon. Loss: 0.013458749149309793
Trial 19, Epoch 21/30, Train Loss: 0.0161, Val Loss: 0.0162, KL Weight: 0.0005, Train Recon. Loss: 0.0131, Val Recon. Loss: 0.013254463019968129
Trial 19, Epoch 22/30, Train Loss: 0.0150, Val Loss: 0.0186, KL Weight: 0.0005, Train Recon. Loss: 0.0120, Val Recon. Loss: 0.01558348348817641
Trial 19, Epoch 23/30, Train Loss: 0.0151, Val Loss: 0.0240, KL Weight: 0.0005, Train Recon. Loss: 0.0121, Val Recon. Loss: 0.02099173574767923
Trial 19, Epoch 24/30, Train Loss: 0.0147, Val Loss: 0.0143, KL Weight: 0.0005, Train Recon. Loss: 0.0116, Val Recon. Loss: 0.011176896985327908
Trial 19, Epoch 25/30, Train Loss: 0.0146, Val Loss: 0.0143, KL Weight: 0.0005, Train Recon. Loss: 0.0115, Val Recon. Loss: 0.011231628638784982
Trial 19, Epoch 26/30, Train Loss: 0.0141, Val Loss: 0.0140, KL Weight: 0.0005, Train Recon. Loss: 0.0109, Val Recon. Loss: 0.010835753950374411
Trial 19, Epoch 27/30, Train Loss: 0.0140, Val Loss: 0.0147, KL Weight: 0.0005, Train Recon. Loss: 0.0109, Val Recon. Loss: 0.011551309527682239
Trial 19, Epoch 28/30, Train Loss: 0.0135, Val Loss: 0.0150, KL Weight: 0.0005, Train Recon. Loss: 0.0103, Val Recon. Loss: 0.011751621165242802
Trial 19, Epoch 29/30, Train Loss: 0.0134, Val Loss: 0.0157, KL Weight: 0.0005, Train Recon. Loss: 0.0102, Val Recon. Loss: 0.012471351551445187

[I 2025-02-16 21:48:37,196] Trial 19 finished with value: 0.013183182211246173 and parameters: {'lr': 0.00012072285661277648, 'batch_size': 256, 'hidden_size1': 64, 'hidden_size2': 64, 'hidden_size3': 56}. Best is trial 9 with value: 0.011827676282246785.

Trial 19, Epoch 30/30, Train Loss: 0.0129, Val Loss: 0.0164, KL Weight: 0.0005, Train Recon. Loss: 0.0096, Val Recon. Loss: 0.013183182211246173
Best trial:
  Final Validation Loss (MAE): 0.0118
  Params:
    lr: 0.0001804978313277879
    batch_size: 256
    hidden_size1: 48
    hidden_size2: 64
    hidden_size3: 32

    number     value             datetime_start          datetime_complete  \
0        0  0.021200 2025-02-16 21:02:50.372783 2025-02-16 21:05:30.450920
1        1  0.122647 2025-02-16 21:05:30.451800 2025-02-16 21:08:12.698868
2        2  0.112908 2025-02-16 21:08:12.699495 2025-02-16 21:12:16.578546
3        3  0.064287 2025-02-16 21:12:16.579867 2025-02-16 21:14:53.832103
4        4  0.116382 2025-02-16 21:14:53.832747 2025-02-16 21:18:49.156545
5        5  0.017414 2025-02-16 21:18:49.157497 2025-02-16 21:21:25.609852
6        6  0.018771 2025-02-16 21:21:25.610698 2025-02-16 21:25:21.128646
7        7  0.197662 2025-02-16 21:25:21.129857 2025-02-16 21:25:28.984089
8        8  0.025508 2025-02-16 21:25:28.985034 2025-02-16 21:28:06.432743
9        9  0.011828 2025-02-16 21:28:06.433645 2025-02-16 21:32:00.735398
10      10  0.017407 2025-02-16 21:32:00.736561 2025-02-16 21:35:55.971122
11      11  0.325182 2025-02-16 21:35:55.972271 2025-02-16 21:36:03.818084
12      12  0.111723 2025-02-16 21:36:03.819053 2025-02-16 21:36:11.660491
13      13  0.013954 2025-02-16 21:36:11.661122 2025-02-16 21:40:01.563136
14      14  0.012113 2025-02-16 21:40:01.564291 2025-02-16 21:43:52.883153
15      15  0.097867 2025-02-16 21:43:52.884075 2025-02-16 21:44:16.442431
16      16  0.104044 2025-02-16 21:44:16.443108 2025-02-16 21:44:24.293575
17      17  0.113065 2025-02-16 21:44:24.294629 2025-02-16 21:44:32.155931
18      18  0.103553 2025-02-16 21:44:32.156555 2025-02-16 21:44:40.038169
19      19  0.013183 2025-02-16 21:44:40.038799 2025-02-16 21:48:37.196604

                 duration  params_batch_size  params_hidden_size1  \
0  0 days 00:02:40.078137                512                   80
1  0 days 00:02:42.247068                512                   64
2  0 days 00:04:03.879051                256                   64
3  0 days 00:02:37.252236                512                   32
4  0 days 00:03:55.323798                256                  128
5  0 days 00:02:36.452355                512                   48
6  0 days 00:03:55.517948                256                   96
7  0 days 00:00:07.854232                256                   96
8  0 days 00:02:37.447709                512                   96
9  0 days 00:03:54.301753                256                   48
10 0 days 00:03:55.234561                256                   16
11 0 days 00:00:07.845813                256                   16
12 0 days 00:00:07.841438                256                   16
13 0 days 00:03:49.902014                256                   32
14 0 days 00:03:51.318862                256                   48
15 0 days 00:00:23.558356                256                   48
16 0 days 00:00:07.850467                256                   48
17 0 days 00:00:07.861302                256                   80
18 0 days 00:00:07.881614                256                   32
19 0 days 00:03:57.157805                256                   64

    params_hidden_size2  params_hidden_size3  params_lr     state
0                    16                   24   0.000038  COMPLETE
1                   112                   64   0.008297  COMPLETE
2                   112                   64   0.003008  COMPLETE
3                    64                   40   0.000011  COMPLETE
4                   112                   48   0.003726  COMPLETE
5                    80                   24   0.000447  COMPLETE
6                   128                   16   0.000016  COMPLETE
7                   112                   24   0.018946    PRUNED
8                    96                   64   0.000147  COMPLETE
9                    64                   32   0.000180  COMPLETE
10                   48                    8   0.000368  COMPLETE
11                   48                    8   0.098175    PRUNED
12                   32                    8   0.000261    PRUNED
13                   64                   40   0.000077  COMPLETE
14                   64                   40   0.000076  COMPLETE
15                   80                   48   0.001102    PRUNED
16                   48                   32   0.000055    PRUNED
17                   32                   48   0.000926    PRUNED
18                   80                   32   0.000032    PRUNED
19                   64                   56   0.000121  COMPLETE

In [19]:
trials_df

,number,value,datetime_start,datetime_complete,duration,params_batch_size,params_hidden_size1,params_hidden_size2,params_hidden_size3,params_lr,state
0,0,0.021200,2025-02-16 21:02:50.372783,2025-02-16 21:05:30.450920,0 days 00:02:40.078137,512,80,16,24,0.000038,COMPLETE
1,1,0.122647,2025-02-16 21:05:30.451800,2025-02-16 21:08:12.698868,0 days 00:02:42.247068,512,64,112,64,0.008297,COMPLETE
2,2,0.112908,2025-02-16 21:08:12.699495,2025-02-16 21:12:16.578546,0 days 00:04:03.879051,256,64,112,64,0.003008,COMPLETE
3,3,0.064287,2025-02-16 21:12:16.579867,2025-02-16 21:14:53.832103,0 days 00:02:37.252236,512,32,64,40,0.000011,COMPLETE
4,4,0.116382,2025-02-16 21:14:53.832747,2025-02-16 21:18:49.156545,0 days 00:03:55.323798,256,128,112,48,0.003726,COMPLETE
5,5,0.017414,2025-02-16 21:18:49.157497,2025-02-16 21:21:25.609852,0 days 00:02:36.452355,512,48,80,24,0.000447,COMPLETE
6,6,0.018771,2025-02-16 21:21:25.610698,2025-02-16 21:25:21.128646,0 days 00:03:55.517948,256,96,128,16,0.000016,COMPLETE
7,7,0.197662,2025-02-16 21:25:21.129857,2025-02-16 21:25:28.984089,0 days 00:00:07.854232,256,96,112,24,0.018946,PRUNED
8,8,0.025508,2025-02-16 21:25:28.985034,2025-02-16 21:28:06.432743,0 days 00:02:37.447709,512,96,96,64,0.000147,COMPLETE
9,9,0.011828,2025-02-16 21:28:06.433645,2025-02-16 21:32:00.735398,0 days 00:03:54.301753,256,48,64,32,0.000180,COMPLETE
10,10,0.017407,2025-02-16 21:32:00.736561,2025-02-16 21:35:55.971122,0 days 00:03:55.234561,256,16,48,8,0.000368,COMPLETE
11,11,0.325182,2025-02-16 21:35:55.972271,2025-02-16 21:36:03.818084,0 days 00:00:07.845813,256,16,48,8,0.098175,PRUNED
12,12,0.111723,2025-02-16 21:36:03.819053,2025-02-16 21:36:11.660491,0 days 00:00:07.841438,256,16,32,8,0.000261,PRUNED
13,13,0.013954,2025-02-16 21:36:11.661122,2025-02-16 21:40:01.563136,0 days 00:03:49.902014,256,32,64,40,0.000077,COMPLETE
14,14,0.012113,2025-02-16 21:40:01.564291,2025-02-16 21:43:52.883153,0 days 00:03:51.318862,256,48,64,40,0.000076,COMPLETE
15,15,0.097867,2025-02-16 21:43:52.884075,2025-02-16 21:44:16.442431,0 days 00:00:23.558356,256,48,80,48,0.001102,PRUNED
16,16,0.104044,2025-02-16 21:44:16.443108,2025-02-16 21:44:24.293575,0 days 00:00:07.850467,256,48,48,32,0.000055,PRUNED
17,17,0.113065,2025-02-16 21:44:24.294629,2025-02-16 21:44:32.155931,0 days 00:00:07.861302,256,80,32,48,0.000926,PRUNED
18,18,0.103553,2025-02-16 21:44:32.156555,2025-02-16 21:44:40.038169,0 days 00:00:07.881614,256,32,80,32,0.000032,PRUNED
19,19,0.013183,2025-02-16 21:44:40.038799,2025-02-16 21:48:37.196604,0 days 00:03:57.157805,256,64,64,56,0.000121,COMPLETE

In [20]:
trials_df_sorted = trials_df.sort_values(by='value')
trials_df_sorted

,number,value,datetime_start,datetime_complete,duration,params_batch_size,params_hidden_size1,params_hidden_size2,params_hidden_size3,params_lr,state
9,9,0.011828,2025-02-16 21:28:06.433645,2025-02-16 21:32:00.735398,0 days 00:03:54.301753,256,48,64,32,0.000180,COMPLETE
14,14,0.012113,2025-02-16 21:40:01.564291,2025-02-16 21:43:52.883153,0 days 00:03:51.318862,256,48,64,40,0.000076,COMPLETE
19,19,0.013183,2025-02-16 21:44:40.038799,2025-02-16 21:48:37.196604,0 days 00:03:57.157805,256,64,64,56,0.000121,COMPLETE
13,13,0.013954,2025-02-16 21:36:11.661122,2025-02-16 21:40:01.563136,0 days 00:03:49.902014,256,32,64,40,0.000077,COMPLETE
10,10,0.017407,2025-02-16 21:32:00.736561,2025-02-16 21:35:55.971122,0 days 00:03:55.234561,256,16,48,8,0.000368,COMPLETE
5,5,0.017414,2025-02-16 21:18:49.157497,2025-02-16 21:21:25.609852,0 days 00:02:36.452355,512,48,80,24,0.000447,COMPLETE
6,6,0.018771,2025-02-16 21:21:25.610698,2025-02-16 21:25:21.128646,0 days 00:03:55.517948,256,96,128,16,0.000016,COMPLETE
0,0,0.021200,2025-02-16 21:02:50.372783,2025-02-16 21:05:30.450920,0 days 00:02:40.078137,512,80,16,24,0.000038,COMPLETE
8,8,0.025508,2025-02-16 21:25:28.985034,2025-02-16 21:28:06.432743,0 days 00:02:37.447709,512,96,96,64,0.000147,COMPLETE
3,3,0.064287,2025-02-16 21:12:16.579867,2025-02-16 21:14:53.832103,0 days 00:02:37.252236,512,32,64,40,0.000011,COMPLETE
15,15,0.097867,2025-02-16 21:43:52.884075,2025-02-16 21:44:16.442431,0 days 00:00:23.558356,256,48,80,48,0.001102,PRUNED
18,18,0.103553,2025-02-16 21:44:32.156555,2025-02-16 21:44:40.038169,0 days 00:00:07.881614,256,32,80,32,0.000032,PRUNED
16,16,0.104044,2025-02-16 21:44:16.443108,2025-02-16 21:44:24.293575,0 days 00:00:07.850467,256,48,48,32,0.000055,PRUNED
12,12,0.111723,2025-02-16 21:36:03.819053,2025-02-16 21:36:11.660491,0 days 00:00:07.841438,256,16,32,8,0.000261,PRUNED
2,2,0.112908,2025-02-16 21:08:12.699495,2025-02-16 21:12:16.578546,0 days 00:04:03.879051,256,64,112,64,0.003008,COMPLETE
17,17,0.113065,2025-02-16 21:44:24.294629,2025-02-16 21:44:32.155931,0 days 00:00:07.861302,256,80,32,48,0.000926,PRUNED
4,4,0.116382,2025-02-16 21:14:53.832747,2025-02-16 21:18:49.156545,0 days 00:03:55.323798,256,128,112,48,0.003726,COMPLETE
1,1,0.122647,2025-02-16 21:05:30.451800,2025-02-16 21:08:12.698868,0 days 00:02:42.247068,512,64,112,64,0.008297,COMPLETE
7,7,0.197662,2025-02-16 21:25:21.129857,2025-02-16 21:25:28.984089,0 days 00:00:07.854232,256,96,112,24,0.018946,PRUNED
11,11,0.325182,2025-02-16 21:35:55.972271,2025-02-16 21:36:03.818084,0 days 00:00:07.845813,256,16,48,8,0.098175,PRUNED